#!/usr/bin/env python3
"""Generate every agent-facing file from the neutral source tree in agent/.

    uv run python scripts/gen-agent-trees.py           write the generated files
    uv run python scripts/gen-agent-trees.py --check   0 fresh, 1 stale/missing/ghost, 2 cannot generate

agent/ is the ONLY place to edit. Generated files carry BANNER_MD (markdown) and are committed;
tests/test_gen_agent_trees.py fails when they drift. Modelled on gen-cli-reference.py:
generate() is pure and never returns a partial result. Write mode never deletes: a file in a
generated folder that the generator did not produce is reported as a GHOST and the run refuses.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

from ruamel.yaml import YAML

PKG = Path(__file__).resolve().parents[1]
REPO = PKG.parents[1]

BANNER_MD = ("<!-- GENERATED by tools/x4validate/scripts/gen-agent-trees.py from agent/. "
             "Do not edit: regenerate. -->")
# CLAUDE.md is loaded into every session and held under 40,000 characters, so it carries the
# shortest banner that still names the source (plan 1 ruling: the full one pushed it to 40,072).
BANNER_CLAUDE_MD = "<!-- GENERATED from agent/ -->"
TOKEN = "{{TOOLKIT}}"
CLAUDE_TOOLKIT = "$CLAUDE_PROJECT_DIR"
TIER_MODEL = {"fast": "haiku", "balanced": "sonnet", "deep": "opus"}
OWNED: tuple[str, ...] = ("CLAUDE.md", "AGENTS.md", ".claude/agents/", ".claude/skills/",
                          ".claude/settings.json", ".claude/hooks/")
#: Codex silently drops AGENTS.md text past this many BYTES (MEASURED 2026-09-30).
AGENTS_MD_MAX_BYTES = 32768
_IGNORED_PARTS = ("__pycache__",)


class GenerationError(Exception):
    pass


def _read(p: Path) -> str:
    if not p.is_file():
        raise GenerationError(f"missing source file: {p}")
    return p.read_bytes().decode("utf-8").replace("\r\n", "\n")


def _norm(b: bytes) -> str:
    return b.decode("utf-8").replace("\r\n", "\n")


def _with_banner_after_first_line(text: str, banner: str) -> str:
    first, _, rest = text.partition("\n")
    return f"{first}\n\n{banner}\n{rest}"


def _with_banner_after_frontmatter(text: str) -> str:
    if not text.startswith("---\n"):
        raise GenerationError("expected YAML frontmatter at the top")
    end = text.index("\n---\n", 4) + len("\n---\n")
    return f"{text[:end]}\n{BANNER_MD}\n{text[end:]}"


# --- Entry files (CLAUDE.md, AGENTS.md): Plan 2 lane A ------------------------------------------
# One agent-neutral core (agent/instructions/core.md) plus a per-agent addendum
# (agent/instructions/<agent>.md). The addendum's line 1 is an H1 that becomes the entry file's
# title; its body (lines 2+) replaces the ONE `{{AGENT_ADDENDUM}}` line in core. Every size or
# shape failure is a GenerationError (rc 2): refuse, never truncate.

ADDENDUM_MARKER = "{{AGENT_ADDENDUM}}"
#: == gates/claude_md_budget.HARD_CEILING (pinned by a test). Counted in CHARACTERS after CRLF->LF,
#: the way the gate's char_count counts them.
CLAUDE_MD_MAX_CHARS = 40_000
#: Below this many bytes of AGENTS.md headroom the generator prints an advisory line; never a refusal.
AGENTS_MD_WARN_HEADROOM = 2_048
#: Per-agent rendering. `tokens` are applied to the assembled entry file; `{{GENERATED_FILES}}`
#: is rendered from OWNED for every agent (one source of truth).
TARGETS: dict[str, dict] = {
    "claude": {"entry": "CLAUDE.md", "addendum": "claude.md", "skills": ".claude/skills/",
               "tokens": {"{{TOOLKIT}}": "$CLAUDE_PROJECT_DIR",
                          "{{PROJECT_DIR}}": "`$CLAUDE_PROJECT_DIR`"}},
    "codex": {"entry": "AGENTS.md", "addendum": "codex.md", "skills": ".agents/skills/",
              # Plan 2 DECISIONS #2: the generated Codex tree carries `$X4_TOOLKIT` (right in
              # bash/zsh); install.ps1 rewrites it to `$env:X4_TOOLKIT`, install.sh leaves it.
              # The in-repo copy cannot know the OS, so AGENTS.md tells Codex-on-Windows to write
              # `$env:X4_TOOLKIT` (MEASURED: in pwsh `$X4_TOOLKIT` expands to EMPTY).
              "tokens": {"{{TOOLKIT}}": "$X4_TOOLKIT",
                         "{{PROJECT_DIR}}": "the folder the agent was started in"}},
}
_LEFTOVER_TOKEN = re.compile(r"\{\{[A-Z_]+\}\}")

#: The core reaches EVERY agent, so it may not name a Claude-only mechanism. Each (regex, reason)
#: is one clause, with one falsification twin per clause in test_gen_agent_trees.py. The remedy
#: for a hit is the agent's addendum (agent/instructions/<agent>.md), never this list.
NEUTRALITY_BANNED: tuple[tuple[str, str], ...] = (
    (r"CLAUDE_PROJECT_DIR", "Claude Code's project variable: write {{PROJECT_DIR}}"),
    (r"\bClaude\b", "names Claude (incl. 'Claude Code'): say 'the agent', or move it to claude.md"),
    (r"CLAUDE\.md", "Claude's entry file: say 'your project instructions'"),
    (r"MEMORY\.md", "Claude Code's auto-memory index"),
    (r"NotebookEdit", "a Claude Code tool name"),
    (r"settings\.json", "Claude Code's hook/settings file"),
    (r"\.claude[/\\]", "a .claude/ path (Claude-only tree)"),
    (r"\*\*Glob\*\*", "the Claude Code Glob tool"),
    (r"\*\*Grep\*\*", "the Claude Code Grep tool"),
)
#: Exact substrings exempted from NEUTRALITY_BANNED. Blanked to equal-length spaces BEFORE
#: matching, so line numbers and the rest of the line are still checked.
NEUTRALITY_ALLOWED: tuple[str, ...] = (
    ".claude\\backups\\",     # the toolkit's backup dir: every agent's backup hook writes it
    ".claude/backups/",       # same, POSIX spelling
    ".claude/x4-paths.env",   # the toolkit's path config until lane C moves it (phase 7)
)


def check_neutral(core: str) -> None:
    """Refuse a core that names a Claude-only mechanism, naming the line and the reason."""
    for n, line in enumerate(core.replace("\r\n", "\n").split("\n"), 1):
        for allowed in NEUTRALITY_ALLOWED:
            line = line.replace(allowed, " " * len(allowed))
        for pattern, reason in NEUTRALITY_BANNED:
            m = re.search(pattern, line)
            if m:
                raise GenerationError(f"agent/instructions/core.md is not agent-neutral: line {n}: "
                                      f"{m.group(0)!r} -- {reason}")


def _generated_files_phrase() -> str:
    return ", ".join(f"`{p}`" for p in OWNED)


def _largest_sections(text: str, n: int = 5) -> str:
    """The n largest `## ` sections with their sizes, so a refusal says where to cut."""
    sizes: list[tuple[int, str]] = []
    head, buf = "(preamble)", []
    for line in text.split("\n") + ["## (end)"]:
        if line.startswith("## "):
            chunk = "\n".join(buf) + "\n"
            sizes.append((len(chunk.encode("utf-8")), head))
            head, buf = line[3:].strip(), [line]
        else:
            buf.append(line)
    sizes.sort(reverse=True)
    return "; ".join(f"{h[:60]!r} {b:,} B" for b, h in sizes[:n])


def render_entry(src: Path, agent: str) -> str:
    """Title (addendum line 1) + banner + core, with the addendum body at the marker."""
    target = TARGETS[agent]
    add_name = f"agent/instructions/{target['addendum']}"
    addendum = _read(src / "instructions" / target["addendum"])
    title, _, add_body = addendum.partition("\n")
    if not title.startswith("# "):
        raise GenerationError(f"{add_name}: line 1 must be the entry file's H1 title ('# ...'), "
                              f"got {title[:60]!r}")
    add_body = add_body.strip("\n")
    if not add_body.strip():
        raise GenerationError(f"{add_name}: the addendum has a title but no body -- every agent's "
                              f"entry file carries agent-specific rules")
    core = _read(src / "instructions" / "core.md")
    count = core.split("\n").count(ADDENDUM_MARKER)
    if count != 1:
        raise GenerationError(f"agent/instructions/core.md must hold exactly ONE {ADDENDUM_MARKER} "
                              f"line, found {count}")
    lines = core.split("\n")
    i = lines.index(ADDENDUM_MARKER)
    lines[i:i + 1] = add_body.split("\n") if add_body else []
    body = "\n".join(lines)
    for token, value in {**target["tokens"], "{{GENERATED_FILES}}": _generated_files_phrase()}.items():
        body = body.replace(token, value)
    left = sorted(set(_LEFTOVER_TOKEN.findall(body)))
    if left:
        raise GenerationError(f"{target['entry']}: unknown token(s) left after rendering: "
                              f"{', '.join(left)}")
    return f"{title}\n\n{BANNER_CLAUDE_MD}\n{body}"


def size_report(out: dict[str, str]) -> list[str]:
    """Advisory sizes of the entry files, in the unit each consumer limits."""
    lines = []
    if "CLAUDE.md" in out:
        lines.append(f"CLAUDE.md {len(out['CLAUDE.md']):,}/{CLAUDE_MD_MAX_CHARS:,} chars")
    if "AGENTS.md" in out:
        size = len(out["AGENTS.md"].encode("utf-8"))
        line = f"AGENTS.md {size:,}/{AGENTS_MD_MAX_BYTES:,} bytes"
        if AGENTS_MD_MAX_BYTES - size < AGENTS_MD_WARN_HEADROOM:
            line += (f"  ADVISORY: only {AGENTS_MD_MAX_BYTES - size:,} bytes of headroom "
                     f"(< {AGENTS_MD_WARN_HEADROOM:,})")
        lines.append(line)
    return lines


def render_claude_md(src: Path) -> str:
    out = render_entry(src, "claude")
    if len(out) > CLAUDE_MD_MAX_CHARS:
        raise GenerationError(f"CLAUDE.md would be {len(out):,} characters, over the "
                              f"{CLAUDE_MD_MAX_CHARS} characters ceiling; largest sections: "
                              f"{_largest_sections(out)}")
    return out


def render_agents_md(src: Path) -> str:
    """AGENTS.md (Codex and other agents). STOPGAP: the Codex addendum alone, until the phase-3
    split brings the shared core under AGENTS_MD_MAX_BYTES. Refuses rather than emitting a
    file Codex would silently truncate."""
    text = _read(src / "instructions" / "codex.md")
    if not text.strip():
        raise GenerationError("agent/instructions/codex.md is empty -- AGENTS.md would say nothing")
    out = _with_banner_after_first_line(text, BANNER_CLAUDE_MD)
    size = len(out.encode("utf-8"))
    if size > AGENTS_MD_MAX_BYTES:
        raise GenerationError(f"AGENTS.md would be {size} bytes; Codex silently drops text past "
                              f"{AGENTS_MD_MAX_BYTES}")
    return out


def render_agent_md(agent_dir: Path) -> tuple[str, str]:
    meta = YAML(typ="safe").load(_read(agent_dir / "agent.yaml"))
    if not isinstance(meta, dict):
        raise GenerationError(f"{agent_dir}/agent.yaml: not a mapping")
    for key in ("name", "description", "tier"):
        if not meta.get(key):
            raise GenerationError(f"{agent_dir}/agent.yaml: missing {key}")
    if meta["tier"] not in TIER_MODEL:
        raise GenerationError(f"{agent_dir}/agent.yaml: unknown tier {meta['tier']!r}")
    tools = (meta.get("claude") or {}).get("tools") or []
    body = _read(agent_dir / "instructions.md").replace(TOKEN, CLAUDE_TOOLKIT)
    lines = ["---", f"name: {meta['name']}", f"description: {meta['description']}"]
    if tools:
        lines.append("tools: " + ", ".join(tools))
    lines += [f"model: {TIER_MODEL[meta['tier']]}", "---", ""]
    text = "\n".join(lines) + "\n" + body
    return f".claude/agents/{meta['name']}.md", _with_banner_after_frontmatter(text)


def render_skills(src: Path) -> dict[str, str]:
    """Every file under agent/skills/<skill>/, TOKEN rendered for Claude. A SKILL.md gets the
    banner after its frontmatter unless it already carries a GENERATED banner of its own
    (x4-cli-reference is generated by gen-cli-reference.py; two banners would be noise)."""
    root = src / "skills"
    skill_dirs = sorted(p for p in root.iterdir() if p.is_dir()) if root.is_dir() else []
    if not skill_dirs:
        raise GenerationError("agent/skills/ holds no skill")
    out: dict[str, str] = {}
    for d in skill_dirs:
        if not (d / "SKILL.md").is_file():
            raise GenerationError(f"{d} has no SKILL.md")
        for f in sorted(d.rglob("*")):
            if not f.is_file() or any(part in _IGNORED_PARTS for part in f.parts):
                continue
            text = _read(f).replace(TOKEN, CLAUDE_TOOLKIT)
            if f.name == "SKILL.md" and "<!-- GENERATED" not in text:
                text = _with_banner_after_frontmatter(text)
            out[".claude/skills/" + f.relative_to(root).as_posix()] = text
    return out


def render_hooks(src: Path) -> dict[str, str]:
    """The guards, copied VERBATIM into .claude/hooks/: no banner (a comment line would move every
    line number the guard tests and mutants anchor on) and no token rewrite (_x4-env.sh uses
    $CLAUDE_PROJECT_DIR as a literal fallback root). Behaviour must not change by a byte."""
    root = src / "guards" / "claude-hooks"
    if not root.is_dir():
        raise GenerationError(f"no guard source at {root}")
    out: dict[str, str] = {}
    for f in sorted(root.rglob("*")):
        if not f.is_file() or any(part in _IGNORED_PARTS + (".pytest_cache",) for part in f.parts):
            continue
        out[".claude/hooks/" + f.relative_to(root).as_posix()] = _read(f)
    if not out:
        raise GenerationError(f"{root} holds no guard")
    return out


def generate(repo: Path) -> dict[str, str]:
    src = repo / "agent"
    if not src.is_dir():
        raise GenerationError(f"no neutral source tree at {src}")
    check_neutral(_read(src / "instructions" / "core.md"))
    out: dict[str, str] = {"CLAUDE.md": render_claude_md(src), "AGENTS.md": render_agents_md(src)}
    agents = src / "agents"
    agent_dirs = sorted(p for p in agents.iterdir() if p.is_dir()) if agents.is_dir() else []
    if not agent_dirs:
        raise GenerationError("agent/agents/ holds no agent")
    for d in agent_dirs:
        rel, text = render_agent_md(d)
        out[rel] = text
    out.update(render_skills(src))
    out.update(render_hooks(src))
    out[".claude/settings.json"] = _read(src / "targets" / "claude" / "settings.json")
    return dict(sorted(out.items()))


def _git_visible(root: Path) -> set[str] | None:
    """Tracked + untracked-but-not-ignored files, or None when root is not a git work tree.
    A file .gitignore excludes (.pytest_cache/, __pycache__/) is never a GHOST."""
    try:
        r = subprocess.run(["git", "-C", str(root), "ls-files", "-co", "--exclude-standard", "-z"],
                           capture_output=True, timeout=60)
    except (OSError, subprocess.TimeoutExpired):
        return None
    if r.returncode != 0:
        return None
    return {p for p in r.stdout.decode("utf-8").split("\0") if p}


def _owned_files(root: Path) -> set[str]:
    visible = _git_visible(root)
    found: set[str] = set()
    for prefix in OWNED:
        p = root / prefix
        if prefix.endswith("/"):
            if p.is_dir():
                for f in p.rglob("*"):
                    rel = f.relative_to(root).as_posix()
                    if not f.is_file() or any(part in _IGNORED_PARTS for part in f.parts):
                        continue
                    if visible is None or rel in visible:
                        found.add(rel)
        elif p.is_file():
            found.add(prefix)
    return found


def problems(expected: dict[str, str], root: Path) -> list[str]:
    out: list[str] = []
    for rel, text in expected.items():
        p = root / rel
        if not p.is_file():
            out.append(f"MISSING  {rel}")
        elif _norm(p.read_bytes()) != text:
            out.append(f"STALE    {rel}")
    for rel in sorted(_owned_files(root) - set(expected)):
        out.append(f"GHOST    {rel}")
    return sorted(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    try:
        expected = generate(REPO)
    except GenerationError as e:
        print(f"REFUSING: {e}", file=sys.stderr)
        return 2
    found = problems(expected, REPO)
    for line in size_report(expected):         # advisory, stdout, every run
        print(line)
    if args.check:
        for line in found:
            print(line, file=sys.stderr)
        return 1 if found else 0
    # Write ONLY what is missing or stale, and name every stale file overwritten: a hand edit to a
    # generated file (a tool writing settings.json, another session's work) must not vanish unseen.
    to_write = [line.split(None, 1)[1] for line in found if line.startswith(("MISSING", "STALE"))]
    for line in found:
        if line.startswith("STALE"):
            print(f"{line}  (overwritten from agent/ -- move a wanted edit into agent/ and regenerate)")
    for rel in to_write:
        p = REPO / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        data = expected[rel].encode("utf-8")   # encode FIRST: a failed encode cannot truncate
        p.write_bytes(data)
    print(f"wrote {len(to_write)} of {len(expected)} file(s); {len(expected) - len(to_write)} already fresh")
    ghosts = [line for line in found if line.startswith("GHOST")]
    if ghosts:                                 # NEVER delete (user decision 2026-10-01): report and refuse
        for line in ghosts:
            print(line, file=sys.stderr)
        print(f"REFUSING to finish: {len(ghosts)} file(s) in generated folders are not generated. "
              "Move them into agent/ or delete them yourself, then re-run.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
