#!/usr/bin/env python3
"""Generate every agent-facing file from the neutral source tree in agent/.

    uv run python scripts/gen-agent-trees.py           write the generated files
    uv run python scripts/gen-agent-trees.py --check   0 fresh, 1 stale/missing/ghost, 2 cannot generate

agent/ is the ONLY place to edit. Generated files carry BANNER_MD (markdown) and are committed;
tests/test_gen_agent_trees.py fails when they drift. Modelled on gen-cli-reference.py:
generate() is pure and never returns a partial result. Write mode never deletes: a file in a
generated folder that the generator did not produce is reported as a GHOST and the run refuses.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

from ruamel.yaml import YAML
from ruamel.yaml.error import YAMLError

PKG = Path(__file__).resolve().parents[1]
REPO = PKG.parents[1]

BANNER_MD = ("<!-- GENERATED by tools/x4validate/scripts/gen-agent-trees.py from agent/. "
             "Do not edit: regenerate. -->")
# CLAUDE.md is loaded into every session and held under 40,000 characters, so it carries the
# shortest banner that still names the source (plan 1 ruling: the full one pushed it to 40,072).
BANNER_CLAUDE_MD = "<!-- GENERATED from agent/ -->"
TOKEN = "{{TOOLKIT}}"
CLAUDE_TOOLKIT = "$CLAUDE_PROJECT_DIR"
TIER_MODEL = {"fast": "haiku", "balanced": "sonnet", "deep": "opus"}
OWNED: tuple[str, ...] = ("CLAUDE.md", "AGENTS.md", ".claude/agents/", ".claude/skills/",
                          ".claude/settings.json", ".claude/hooks/", ".agents/skills/")
#: Codex silently drops AGENTS.md text past this many BYTES (MEASURED 2026-09-30).
AGENTS_MD_MAX_BYTES = 32768
_IGNORED_PARTS = ("__pycache__",)
#: Claude Code agent names are lowercase letters, digits and hyphens; anything else could also
#: steer the output path (MEASURED: '../../escaped' rendered outside .claude/agents/).
_AGENT_NAME = re.compile(r"^[a-z0-9][a-z0-9-]*$")
#: Every key agent.yaml may carry; anything else refuses (release review R3-5).
AGENT_KEYS = frozenset({"name", "description", "tier", "read_only", "claude"})
AGENT_CLAUDE_KEYS = frozenset({"tools"})
#: `read_only: true` refuses these in claude.tools. Bash is NOT policed: a shell can write, so
#: read_only states intent and keeps the file-editing tools out; it is no sandbox.
WRITE_TOOLS = frozenset({"Edit", "MultiEdit", "Write", "NotebookEdit"})


class GenerationError(Exception):
    pass


def _read(p: Path) -> str:
    if not p.is_file():
        raise GenerationError(f"missing source file: {p}")
    try:
        return p.read_bytes().decode("utf-8").replace("\r\n", "\n")
    except UnicodeDecodeError as e:
        raise GenerationError(f"{p}: not UTF-8 (byte 0x{e.object[e.start]:02x} at offset {e.start})") from e


def _norm(b: bytes) -> str | None:
    """A generated file's text, or None when it is not UTF-8 -- which problems() reports as
    STALE (None never equals the expected text) instead of crashing --check."""
    try:
        return b.decode("utf-8").replace("\r\n", "\n")
    except UnicodeDecodeError:
        return None


def _load_yaml(p: Path):
    """A YAML source, or GenerationError naming the file (DuplicateKeyError is a YAMLError too)."""
    try:
        return YAML(typ="safe").load(_read(p))
    except YAMLError as e:
        raise GenerationError(f"{p}: not valid YAML: {str(e).splitlines()[0]}") from e


def _yaml_scalar(s: str) -> str:
    """s as a YAML value: plain when YAML reads it back unchanged (every real description today,
    MEASURED), else a JSON string, which is a valid YAML double-quoted scalar."""
    try:
        if YAML(typ="safe").load("k: " + s) == {"k": s}:
            return s
    except YAMLError:
        pass
    return json.dumps(s, ensure_ascii=False)


def _with_banner_after_first_line(text: str, banner: str) -> str:
    first, _, rest = text.partition("\n")
    return f"{first}\n\n{banner}\n{rest}"


def _with_banner_after_frontmatter(text: str, where: object) -> str:
    end = text.find("\n---\n", 4)
    if not text.startswith("---\n") or end < 0:
        raise GenerationError(f"{where}: YAML frontmatter must open and close with '---' lines")
    end += len("\n---\n")
    return f"{text[:end]}\n{BANNER_MD}\n{text[end:]}"


# --- Entry files (CLAUDE.md, AGENTS.md): Plan 2 lane A ------------------------------------------
# One agent-neutral core (agent/instructions/core.md) plus a per-agent addendum
# (agent/instructions/<agent>.md). The addendum's line 1 is an H1 that becomes the entry file's
# title; its body (lines 2+) replaces the ONE `{{AGENT_ADDENDUM}}` line in core. Every size or
# shape failure is a GenerationError (rc 2): refuse, never truncate.

ADDENDUM_MARKER = "{{AGENT_ADDENDUM}}"
#: == gates/claude_md_budget.HARD_CEILING (pinned by a test). Counted in CHARACTERS after CRLF->LF,
#: the way the gate's char_count counts them.
CLAUDE_MD_MAX_CHARS = 40_000
#: Below this many bytes of AGENTS.md headroom the generator prints an advisory line; never a refusal.
AGENTS_MD_WARN_HEADROOM = 2_048
#: Per-agent rendering. `tokens` are applied to the assembled entry file; `{{GENERATED_FILES}}`
#: is rendered from OWNED for every agent (one source of truth).
TARGETS: dict[str, dict] = {
    "claude": {"entry": "CLAUDE.md", "addendum": "claude.md", "skills": ".claude/skills/",
               "tokens": {"{{TOOLKIT}}": "$CLAUDE_PROJECT_DIR",
                          "{{PROJECT_DIR}}": "`$CLAUDE_PROJECT_DIR`"}},
    "codex": {"entry": "AGENTS.md", "addendum": "codex.md", "skills": ".agents/skills/",
              # Plan 2 user decision #2: the generated Codex/generic SKILLS keep `{{TOOLKIT}}`
              # verbatim and the INSTALLER renders it per OS (`$env:X4_TOOLKIT` on Windows, where
              # Codex runs PowerShell and `$X4_TOOLKIT` expands to EMPTY -- MEASURED; `$X4_TOOLKIT`
              # elsewhere). The in-repo copy cannot know the OS. Rendering it here (as this table
              # did until Plan 3 lane J) left the installers' rewrite nothing to find.
              "skill_toolkit": TOKEN,
              "tokens": {"{{TOOLKIT}}": "$X4_TOOLKIT",
                         "{{PROJECT_DIR}}": "the folder the agent was started in"}},
}
#: OpenCode (Plan 3 lane L, best effort): no entry file of its own -- it reads AGENTS.md (READ,
#: opencode.ai/docs/rules) -- plus .opencode/X4-OPENCODE.md, which the per-machine
#: .opencode/opencode.jsonc names under `instructions`. Skills render exactly as Codex's (the same
#: token: whatever fixes the Codex skill token fixes both).
TARGETS["opencode"] = {"entry": None, "addendum": "opencode.md", "skills": ".opencode/skills/",
                       "skill_toolkit": TARGETS["codex"]["skill_toolkit"],
                       "tokens": dict(TARGETS["codex"]["tokens"])}
_LEFTOVER_TOKEN = re.compile(r"\{\{[A-Z_]+\}\}")

#: The core reaches EVERY agent, so it may not name a Claude-only mechanism. Each (regex, reason)
#: is one clause, with one falsification twin per clause in test_gen_agent_trees.py. The remedy
#: for a hit is the agent's addendum (agent/instructions/<agent>.md), never this list.
NEUTRALITY_BANNED: tuple[tuple[str, str], ...] = (
    (r"CLAUDE_PROJECT_DIR", "Claude Code's project variable: write {{PROJECT_DIR}}"),
    (r"\bClaude\b", "names Claude (incl. 'Claude Code'): say 'the agent', or move it to claude.md"),
    (r"CLAUDE\.md", "Claude's entry file: say 'your project instructions'"),
    (r"MEMORY\.md", "Claude Code's auto-memory index"),
    (r"NotebookEdit", "a Claude Code tool name"),
    (r"settings\.json", "Claude Code's hook/settings file"),
    (r"\.claude[/\\]", "a .claude/ path (Claude-only tree)"),
    (r"\*\*Glob\*\*", "the Claude Code Glob tool"),
    (r"\*\*Grep\*\*", "the Claude Code Grep tool"),
)
#: Exact substrings exempted from NEUTRALITY_BANNED. Blanked to equal-length spaces BEFORE
#: matching, so line numbers and the rest of the line are still checked.
NEUTRALITY_ALLOWED: tuple[str, ...] = (
    ".claude\\backups\\",     # the toolkit's backup dir: every agent's backup hook writes it
    ".claude/backups/",       # same, POSIX spelling
)


def check_neutral(core: str, where: str = "agent/instructions/core.md") -> None:
    """Refuse a core that names a Claude-only mechanism, naming the line and the reason. `where`
    names the source in the refusal (the OpenCode addendum is checked by the same list)."""
    for n, line in enumerate(core.replace("\r\n", "\n").split("\n"), 1):
        for allowed in NEUTRALITY_ALLOWED:
            line = line.replace(allowed, " " * len(allowed))
        for pattern, reason in NEUTRALITY_BANNED:
            m = re.search(pattern, line)
            if m:
                raise GenerationError(f"{where} is not agent-neutral: line {n}: "
                                      f"{m.group(0)!r} -- {reason}")


def _generated_files_phrase() -> str:
    return ", ".join(f"`{p}`" for p in OWNED)


def _largest_sections(text: str, n: int = 5) -> str:
    """The n largest `## ` sections with their sizes, so a refusal says where to cut."""
    sizes: list[tuple[int, str]] = []
    head, buf = "(preamble)", []
    for line in text.split("\n") + ["## (end)"]:
        if line.startswith("## "):
            chunk = "\n".join(buf) + "\n"
            sizes.append((len(chunk.encode("utf-8")), head))
            head, buf = line[3:].strip(), [line]
        else:
            buf.append(line)
    sizes.sort(reverse=True)
    return "; ".join(f"{h[:60]!r} {b:,} B" for b, h in sizes[:n])


def render_entry(src: Path, agent: str) -> str:
    """Title (addendum line 1) + banner + core, with the addendum body at the marker."""
    target = TARGETS[agent]
    add_name = f"agent/instructions/{target['addendum']}"
    addendum = _read(src / "instructions" / target["addendum"])
    title, _, add_body = addendum.partition("\n")
    if not title.startswith("# "):
        raise GenerationError(f"{add_name}: line 1 must be the entry file's H1 title ('# ...'), "
                              f"got {title[:60]!r}")
    add_body = add_body.strip("\n")
    if not add_body.strip():
        raise GenerationError(f"{add_name}: the addendum has a title but no body -- every agent's "
                              f"entry file carries agent-specific rules")
    core = _read(src / "instructions" / "core.md")
    count = core.split("\n").count(ADDENDUM_MARKER)
    if count != 1:
        raise GenerationError(f"agent/instructions/core.md must hold exactly ONE {ADDENDUM_MARKER} "
                              f"line, found {count}")
    lines = core.split("\n")
    i = lines.index(ADDENDUM_MARKER)
    lines[i:i + 1] = add_body.split("\n") if add_body else []
    body = "\n".join(lines)
    for token, value in {**target["tokens"], "{{GENERATED_FILES}}": _generated_files_phrase()}.items():
        body = body.replace(token, value)
    left = sorted(set(_LEFTOVER_TOKEN.findall(body)))
    if left:
        raise GenerationError(f"{target['entry']}: unknown token(s) left after rendering: "
                              f"{', '.join(left)}")
    return f"{title}\n\n{BANNER_CLAUDE_MD}\n{body}"


def size_report(out: dict[str, str]) -> list[str]:
    """Advisory sizes of the entry files, in the unit each consumer limits."""
    lines = []
    if "CLAUDE.md" in out:
        lines.append(f"CLAUDE.md {len(out['CLAUDE.md']):,}/{CLAUDE_MD_MAX_CHARS:,} chars")
    if "AGENTS.md" in out:
        size = len(out["AGENTS.md"].encode("utf-8"))
        line = f"AGENTS.md {size:,}/{AGENTS_MD_MAX_BYTES:,} bytes"
        if AGENTS_MD_MAX_BYTES - size < AGENTS_MD_WARN_HEADROOM:
            line += (f"  ADVISORY: only {AGENTS_MD_MAX_BYTES - size:,} bytes of headroom "
                     f"(< {AGENTS_MD_WARN_HEADROOM:,})")
        lines.append(line)
    return lines


def render_claude_md(src: Path) -> str:
    out = render_entry(src, "claude")
    if len(out) > CLAUDE_MD_MAX_CHARS:
        raise GenerationError(f"CLAUDE.md would be {len(out):,} characters, over the "
                              f"{CLAUDE_MD_MAX_CHARS} characters ceiling; largest sections: "
                              f"{_largest_sections(out)}")
    return out


def render_agents_md(src: Path) -> str:
    """AGENTS.md (Codex and other agents) = the shared core + the Codex addendum. Refuses rather
    than emitting a file Codex would silently truncate (counted in BYTES: Codex cuts at exactly
    32,768, MEASURED 2026-10-02 on 0.160.0, and a nested AGENTS.md shares the same budget)."""
    out = render_entry(src, "codex")
    size = len(out.encode("utf-8"))
    if size > AGENTS_MD_MAX_BYTES:
        raise GenerationError(f"AGENTS.md would be {size} bytes; Codex silently drops text past "
                              f"{AGENTS_MD_MAX_BYTES}; largest sections: {_largest_sections(out)}")
    return out


def render_agent_md(agent_dir: Path) -> tuple[str, str]:
    """agent.yaml contract: name matches _AGENT_NAME; description a non-empty string (emitted
    plain when YAML round-trips it, else JSON-quoted); tier in TIER_MODEL; claude, if present, a
    mapping; claude.tools, if present, a YAML LIST of tool names; no key outside AGENT_KEYS /
    AGENT_CLAUDE_KEYS; read_only, if present, a bool, and when true an explicit tools list with
    no WRITE_TOOLS in it. MEASURED before this: a tools
    STRING rendered as 'G, l, o, b', a ': ' in a description produced frontmatter that does not
    parse, and a name of '../../escaped' rendered outside .claude/agents/."""
    p = agent_dir / "agent.yaml"
    meta = _load_yaml(p)
    if not isinstance(meta, dict):
        raise GenerationError(f"{p}: not a mapping")
    # An unknown key is a refusal, never a silent drop (release review R3-5, MEASURED: a typo
    # `tool:` was dropped, the agent rendered with no tools line, and Claude Code then grants a
    # subagent EVERY tool).
    unknown = sorted(set(map(str, meta)) - AGENT_KEYS)
    if unknown:
        raise GenerationError(f"{p}: unknown key(s) {', '.join(unknown)} -- "
                              f"allowed: {', '.join(sorted(AGENT_KEYS))}")
    for key in ("name", "description", "tier"):
        if not meta.get(key):
            raise GenerationError(f"{p}: missing {key}")
        if not isinstance(meta[key], str) or not meta[key].strip():
            raise GenerationError(f"{p}: {key} must be a non-empty string")
    if not _AGENT_NAME.match(meta["name"]):
        raise GenerationError(f"{p}: name {meta['name']!r} must match {_AGENT_NAME.pattern}")
    if meta["tier"] not in TIER_MODEL:
        raise GenerationError(f"{p}: unknown tier {meta['tier']!r}")
    claude = meta.get("claude") or {}
    if not isinstance(claude, dict):
        raise GenerationError(f"{p}: claude must be a mapping")
    unknown = sorted(set(map(str, claude)) - AGENT_CLAUDE_KEYS)
    if unknown:
        raise GenerationError(f"{p}: unknown key(s) {', '.join('claude.' + k for k in unknown)} -- "
                              f"allowed: {', '.join('claude.' + k for k in sorted(AGENT_CLAUDE_KEYS))}")
    tools = claude.get("tools") or []
    if not isinstance(tools, list) or not all(
            isinstance(t, str) and t.strip() and "," not in t and "\n" not in t for t in tools):
        raise GenerationError(f"{p}: claude.tools must be a YAML list of tool names, e.g. [Read, Grep]")
    read_only = meta.get("read_only", False)
    if not isinstance(read_only, bool):
        raise GenerationError(f"{p}: read_only must be true or false, got {read_only!r}")
    if read_only:
        # No tools line = Claude Code grants every tool, write tools included.
        if not tools:
            raise GenerationError(f"{p}: read_only: true needs an explicit claude.tools list -- "
                                  f"without one Claude Code grants every tool")
        writers = sorted(set(tools) & WRITE_TOOLS)
        if writers:
            raise GenerationError(f"{p}: read_only: true but claude.tools grants file-writing "
                                  f"tool(s) {', '.join(writers)}")
    body = _read(agent_dir / "instructions.md").replace(TOKEN, CLAUDE_TOOLKIT)
    model = TIER_MODEL[meta["tier"]]
    lines = ["---", f"name: {meta['name']}", f"description: {_yaml_scalar(meta['description'])}"]
    if tools:
        lines.append("tools: " + ", ".join(tools))
    lines += [f"model: {model}", "---", ""]
    # Belt and braces (#36): re-read what was rendered, so a value class not foreseen above
    # refuses here instead of shipping a frontmatter Claude Code would misread.
    try:
        back = YAML(typ="safe").load("\n".join(lines[1:-2]))
    except YAMLError as e:
        raise GenerationError(f"{p}: rendered frontmatter does not parse: {str(e).splitlines()[0]}") from e
    if not isinstance(back, dict) or (back.get("name"), back.get("description"), back.get("model")) != (
            meta["name"], meta["description"], model):
        raise GenerationError(f"{p}: rendered frontmatter does not read back as its source")
    text = "\n".join(lines) + "\n" + body
    return f".claude/agents/{meta['name']}.md", _with_banner_after_frontmatter(text, p)


def render_skills(src: Path, agent: str = "claude") -> dict[str, str]:
    """Every file under agent/skills/<skill>/, TOKEN rendered for `agent` and placed under that
    agent's skills dir (TARGETS): .claude/skills/ for Claude, .agents/skills/ for Codex and
    generic agents. Frontmatter passes through verbatim (Codex ignores `allowed-tools`, MEASURED
    on 0.154 and 0.160.0). A SKILL.md gets the banner after its frontmatter unless it already
    carries a GENERATED banner of its own (x4-cli-reference is generated by
    gen-cli-reference.py; two banners would be noise)."""
    prefix = TARGETS[agent]["skills"]
    toolkit = TARGETS[agent].get("skill_toolkit", TARGETS[agent]["tokens"][TOKEN])
    root = src / "skills"
    skill_dirs = sorted(p for p in root.iterdir() if p.is_dir()) if root.is_dir() else []
    if not skill_dirs:
        raise GenerationError("agent/skills/ holds no skill")
    out: dict[str, str] = {}
    for d in skill_dirs:
        if not (d / "SKILL.md").is_file():
            raise GenerationError(f"{d} has no SKILL.md")
        for f in sorted(d.rglob("*")):
            if not f.is_file() or any(part in _IGNORED_PARTS for part in f.parts):
                continue
            text = _read(f).replace(TOKEN, toolkit)
            if f.name == "SKILL.md" and "<!-- GENERATED" not in text:
                text = _with_banner_after_frontmatter(text, f)
            out[prefix + f.relative_to(root).as_posix()] = text
    return out


def render_hooks(src: Path) -> dict[str, str]:
    """The guards, copied VERBATIM into .claude/hooks/: no banner (a comment line would move every
    line number the guard tests and mutants anchor on) and no token rewrite (_x4-env.sh uses
    $CLAUDE_PROJECT_DIR as a literal fallback root). Behaviour must not change by a byte."""
    root = src / "guards" / "claude-hooks"
    if not root.is_dir():
        raise GenerationError(f"no guard source at {root}")
    out: dict[str, str] = {}
    for f in sorted(root.rglob("*")):
        if not f.is_file() or any(part in _IGNORED_PARTS + (".pytest_cache",) for part in f.parts):
            continue
        out[".claude/hooks/" + f.relative_to(root).as_posix()] = _read(f)
    if not out:
        raise GenerationError(f"{root} holds no guard")
    return out


# ----------------------------------------------------------------------- Codex (lane B) --- #
#: The Codex target tree. .codex/hooks/ = every guard VERBATIM (so a Codex-only install needs
#: no .claude/) plus the adapter files below; hooks.json is NOT generated here: it carries the
#: absolute project root (Codex substitutes no project variable, and the root is part of the
#: trust hash), so deploy and the installers render it with render_codex_hooks_json(root).
OWNED += (".codex/hooks/", ".codex/rules/")
CODEX_ADAPTERS: dict[str, str] = {
    "codex.py": "codex_adapter.py", "patch_paths.py": "patch_paths.py", "codex_trust.py": "codex_trust.py",
    "codex-entry.ps1": "codex-entry.ps1", "codex-entry.sh": "codex-entry.sh",
}
CODEX_HOOKS_TEMPLATE = Path("targets") / "codex" / "hooks.json.tmpl"
#: cmd.exe runs every Codex hook on Windows (`%COMSPEC% /C`, READ): it expands %VAR% even
#: inside quotes, and a quote or a newline would end the argument. Such a root is refused.
_UNSAFE_ROOT_CHARS = ('"', "\n", "\r", "%")


def render_codex_hooks(src: Path) -> dict[str, str]:
    guards = render_hooks(src)
    out = {".codex/hooks/" + rel[len(".claude/hooks/"):]: text for rel, text in guards.items()}
    root = src / "guards" / "adapters"
    for name, dest in CODEX_ADAPTERS.items():
        out[".codex/hooks/" + dest] = _read(root / name)
    clash = set(CODEX_ADAPTERS.values()) & {rel[len(".claude/hooks/"):] for rel in guards}
    if clash:
        raise GenerationError(f"a Codex adapter file would overwrite a guard: {sorted(clash)}")
    return out


def render_codex_hooks_json(root: Path, src: Path | None = None) -> str:
    """The project's .codex/hooks.json from the FROZEN template, for an install at `root`.
    `{{ROOT}}` gets the forward-slash form (POSIX `command`), `{{ROOT_WIN}}` the backslash form
    (`commandWindows`), each JSON-escaped. Refuses a root cmd.exe would mangle."""
    import json as _json
    root_s = str(root)
    bad = [c for c in _UNSAFE_ROOT_CHARS if c in root_s]
    if bad:
        raise GenerationError(f"refusing a Codex hook root containing {bad!r}: {root_s!r}")
    tmpl = _read((src or REPO / "agent") / CODEX_HOOKS_TEMPLATE)
    posix = _json.dumps(root_s.replace("\\", "/"))[1:-1]
    win = _json.dumps(root_s.replace("/", "\\"))[1:-1]
    text = tmpl.replace("{{ROOT_WIN}}", win).replace("{{ROOT}}", posix)
    if "{{" in text:
        raise GenerationError("hooks.json template has an unrendered token")
    _json.loads(text)                      # a template that renders to invalid JSON never ships
    return text


CODEX_RULES_SOURCE = Path("rules") / "codex-rules.yaml"
CODEX_RULE_BUCKETS = ("forbidden", "prompt", "hook_only")


def render_codex_rules(src: Path) -> str:
    """.codex/rules/x4.rules from agent/rules/codex-rules.yaml: one prefix_rule per forbidden or
    prompt row, with its match/not_match examples INLINE so Codex itself refuses to load a rule
    whose examples are wrong (MEASURED: a wrong example is a policy PARSE error)."""
    import json as _json
    rows = YAML(typ="safe").load(_read(src / CODEX_RULES_SOURCE))
    if not isinstance(rows, list) or not rows:
        raise GenerationError(f"agent/{CODEX_RULES_SOURCE.as_posix()} holds no rows")
    ids = [r.get("id") for r in rows if isinstance(r, dict)]
    if len(ids) != len(rows) or len(set(ids)) != len(ids) or not all(ids):
        raise GenerationError("codex-rules.yaml: every row needs a unique id")
    lines = ["# GENERATED by tools/x4validate/scripts/gen-agent-trees.py from agent/rules/codex-rules.yaml.",
             "# Do not edit: regenerate. These are a SECOND layer; the hooks in .codex/hooks are the guard."]
    for r in rows:
        if r.get("bucket") not in CODEX_RULE_BUCKETS:
            raise GenerationError(f"codex-rules.yaml {r['id']}: bucket must be one of {CODEX_RULE_BUCKETS}")
        if r["bucket"] == "hook_only":
            continue
        for key in ("pattern", "match", "not_match", "justification"):
            if not r.get(key):
                raise GenerationError(f"codex-rules.yaml {r['id']}: a {r['bucket']} rule needs {key}")
        just = f"{r['justification']} (X4 toolkit rule {r['id']})"
        lines += ["", "prefix_rule(",
                  f"    pattern = {_json.dumps(r['pattern'])},",
                  f"    decision = {_json.dumps(r['bucket'])},",
                  f"    justification = {_json.dumps(just)},",
                  f"    match = {_json.dumps(r['match'])},",
                  f"    not_match = {_json.dumps(r['not_match'])},",
                  ")"]
    return "\n".join(lines) + "\n"


def render_codex_tree(src: Path) -> dict[str, str]:
    out = render_codex_hooks(src)
    out[".codex/rules/x4.rules"] = render_codex_rules(src)
    return out


# ------------------------------------------------------------------ OpenCode (Plan 3 lane L) --- #
#: The OpenCode target tree, BEST EFFORT (from docs and source, not measured). .opencode/hooks/ =
#: every guard VERBATIM plus the adapters below. Owned paths are named one by one: OpenCode itself
#: writes .opencode/.gitignore, a user's own plugin in .opencode/plugins/ is not ours, and
#: .opencode/opencode.jsonc is rendered per machine at install (never generated, never committed).
OWNED += (".opencode/hooks/", ".opencode/plugins/x4guard.js", ".opencode/skills/",
          ".opencode/X4-OPENCODE.md")
OPENCODE_ADAPTERS: dict[str, str] = {"patch_paths.py": "patch_paths.py", "codex.py": "codex_adapter.py",
                                     "opencode.py": "opencode_adapter.py", "opencode_config.py": "opencode_config.py"}
OPENCODE_ADDENDUM = ".opencode/X4-OPENCODE.md"
OPENCODE_PLUGIN_SOURCE = Path("targets") / "opencode" / "x4guard.js"


def render_opencode_tree(src: Path) -> dict[str, str]:
    guards = render_hooks(src)
    out = {".opencode/hooks/" + rel[len(".claude/hooks/"):]: text for rel, text in guards.items()}
    root = src / "guards" / "adapters"
    for name, dest in OPENCODE_ADAPTERS.items():
        out[".opencode/hooks/" + dest] = _read(root / name)
    clash = set(OPENCODE_ADAPTERS.values()) & {rel[len(".claude/hooks/"):] for rel in guards}
    if clash:
        raise GenerationError(f"an OpenCode adapter file would overwrite a guard: {sorted(clash)}")
    plugin = _read(src / OPENCODE_PLUGIN_SOURCE)
    out[".opencode/plugins/x4guard.js"] = (
        "// GENERATED by tools/x4validate/scripts/gen-agent-trees.py from "
        f"agent/{OPENCODE_PLUGIN_SOURCE.as_posix()}. Do not edit: regenerate.\n" + plugin)
    out.update(render_skills(src, "opencode"))
    add_name = "agent/instructions/" + TARGETS["opencode"]["addendum"]
    addendum = _read(src / "instructions" / TARGETS["opencode"]["addendum"])
    if not addendum.startswith("# "):
        raise GenerationError(f"{add_name}: line 1 must be an H1 title ('# ...')")
    check_neutral(addendum, add_name)
    out[OPENCODE_ADDENDUM] = _with_banner_after_first_line(addendum, BANNER_MD)
    return out


def generate(repo: Path) -> dict[str, str]:
    src = repo / "agent"
    if not src.is_dir():
        raise GenerationError(f"no neutral source tree at {src}")
    check_neutral(_read(src / "instructions" / "core.md"))
    out: dict[str, str] = {"CLAUDE.md": render_claude_md(src), "AGENTS.md": render_agents_md(src)}
    agents = src / "agents"
    agent_dirs = sorted(p for p in agents.iterdir() if p.is_dir()) if agents.is_dir() else []
    if not agent_dirs:
        raise GenerationError("agent/agents/ holds no agent")
    seen: dict[str, Path] = {}
    for d in agent_dirs:
        rel, text = render_agent_md(d)
        if rel in seen:                 # MEASURED before: the second silently replaced the first
            raise GenerationError(f"agent name {Path(rel).stem!r} is used by both {seen[rel]} and {d}")
        seen[rel] = d
        out[rel] = text
    out.update(render_skills(src, "claude"))
    out.update(render_skills(src, "codex"))
    out.update(render_hooks(src))
    out.update(render_codex_tree(src))
    out.update(render_opencode_tree(src))
    out[".claude/settings.json"] = _read(src / "targets" / "claude" / "settings.json")
    return dict(sorted(out.items()))


def _git_visible(root: Path) -> set[str] | None:
    """Tracked + untracked-but-not-ignored files, or None when root is not a git work tree.
    A file .gitignore excludes (.pytest_cache/, __pycache__/) is never a GHOST."""
    try:
        r = subprocess.run(["git", "-C", str(root), "ls-files", "-co", "--exclude-standard", "-z"],
                           capture_output=True, timeout=60)
    except (OSError, subprocess.TimeoutExpired):
        return None
    if r.returncode != 0:
        return None
    return {p for p in r.stdout.decode("utf-8").split("\0") if p}


def _owned_files(root: Path) -> set[str]:
    visible = _git_visible(root)
    found: set[str] = set()
    for prefix in OWNED:
        p = root / prefix
        if prefix.endswith("/"):
            if p.is_dir():
                for f in p.rglob("*"):
                    rel = f.relative_to(root).as_posix()
                    if not f.is_file() or any(part in _IGNORED_PARTS for part in f.parts):
                        continue
                    if visible is None or rel in visible:
                        found.add(rel)
        elif p.is_file():
            found.add(prefix)
    return found


def problems(expected: dict[str, str], root: Path) -> list[str]:
    out: list[str] = []
    for rel, text in expected.items():
        p = root / rel
        if not p.is_file():
            out.append(f"MISSING  {rel}")
        elif _norm(p.read_bytes()) != text:
            out.append(f"STALE    {rel}")
    for rel in sorted(_owned_files(root) - set(expected)):
        out.append(f"GHOST    {rel}")
    return sorted(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    try:
        expected = generate(REPO)
    except GenerationError as e:
        print(f"REFUSING: {e}", file=sys.stderr)
        return 2
    found = problems(expected, REPO)
    for line in size_report(expected):         # advisory, stdout, every run
        print(line)
    if args.check:
        for line in found:
            print(line, file=sys.stderr)
        return 1 if found else 0
    # Write ONLY what is missing or stale, and name every stale file overwritten: a hand edit to a
    # generated file (a tool writing settings.json, another session's work) must not vanish unseen.
    to_write = [line.split(None, 1)[1] for line in found if line.startswith(("MISSING", "STALE"))]
    for line in found:
        if line.startswith("STALE"):
            print(f"{line}  (overwritten from agent/ -- move a wanted edit into agent/ and regenerate)")
    for rel in to_write:
        p = REPO / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        data = expected[rel].encode("utf-8")   # encode FIRST: a failed encode cannot truncate
        p.write_bytes(data)
    print(f"wrote {len(to_write)} of {len(expected)} file(s); {len(expected) - len(to_write)} already fresh")
    ghosts = [line for line in found if line.startswith("GHOST")]
    if ghosts:                                 # NEVER delete (user decision 2026-10-01): report and refuse
        for line in ghosts:
            print(line, file=sys.stderr)
        print(f"REFUSING to finish: {len(ghosts)} file(s) in generated folders are not generated. "
              "Move them into agent/ or delete them yourself, then re-run.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
