#!/usr/bin/env python3
"""Generate / check scripts/shipped-instruction-hashes.txt -- the CLAUDE.md and AGENTS.md
every RELEASE TAG shipped, as canonical SHA-256 hashes.

Both installers read that file to tell a file the toolkit shipped (safe to replace on an
upgrade) from one its user edited (KEPT, as X4-NOTES.pre-4.0.md / AGENTS.pre-4.0.md). One
data file read by both installers agrees with itself by construction.

Scope: tags matching `v[0-9]*` (user decision H-Q3, 2026-10-02). Blobs are read as BYTES
with `git cat-file`, never through a text pipe, so a CRLF in a blob is seen as it is.

CANONICAL FORM (one definition; the installers each re-implement it natively):
  drop a leading UTF-8 BOM, delete every 0x0D, strip trailing 0x0A bytes, SHA-256, lowercase hex.

Usage (from anywhere):
  python gen-shipped-hashes.py --check   rc 0 = in sync, 1 = drift (rows named), 2 = error
  python gen-shipped-hashes.py --write   rewrite the file from the tags

Maintainers: after tagging a release, run --write and commit the result.
test_shipped_instruction_hashes.py goes red until you do.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import subprocess
import sys

#: .claude/x4-paths.env.example: the 3.x example, retired by an upgrade only when it is an
#: UNEDITED shipped copy (install red-team 2026-10-04: a stale one was left behind).
NAMES = ("CLAUDE.md", "AGENTS.md", ".claude/x4-paths.env.example")
REL = pathlib.PurePosixPath("scripts/shipped-instruction-hashes.txt")
TAG_GLOB = "v[0-9]*"

HEADER = """\
# The CLAUDE.md / AGENTS.md / .claude/x4-paths.env.example every release tag (v[0-9]*)
# shipped, as canonical SHA-256.
# GENERATED by tools/x4validate/scripts/gen-shipped-hashes.py --write; do not edit by hand.
# Canonical form: drop a leading UTF-8 BOM, delete every CR, strip trailing LFs, SHA-256.
# Read by install.sh and install.ps1: a destination file whose hash is listed here is one
# the toolkit shipped, so an upgrade replaces it; any other differing file is KEPT.
# Format: <sha256>  <file name>  <tag[,tag...]>   (the tag column is informational)
"""


def canonical_sha256(data: bytes) -> str:
    if data.startswith(b"\xef\xbb\xbf"):
        data = data[3:]
    return hashlib.sha256(data.replace(b"\r", b"").rstrip(b"\n")).hexdigest()


def _git(repo: pathlib.Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(repo), *args], capture_output=True)


def tags(repo: pathlib.Path) -> list[str]:
    r = _git(repo, "tag", "--list", "--sort=version:refname", TAG_GLOB)
    if r.returncode != 0:
        raise RuntimeError("git tag failed in %s: %s" % (repo, r.stderr.decode(errors="replace")))
    return r.stdout.decode().split()


def expected(repo: pathlib.Path) -> list[tuple[str, str, str]]:
    """(hash, name, "tag,tag") per distinct (hash, name) over every release tag."""
    grouped: dict[tuple[str, str], list[str]] = {}
    for tag in tags(repo):
        for name in NAMES:
            r = _git(repo, "cat-file", "blob", "%s:%s" % (tag, name))
            if r.returncode != 0:
                continue        # this tag did not ship that file
            grouped.setdefault((canonical_sha256(r.stdout), name), []).append(tag)
    return [(h, n, ",".join(t)) for (h, n), t in grouped.items()]


def read_rows(repo: pathlib.Path) -> list[tuple[str, str, str]]:
    f = pathlib.Path(repo) / REL
    if not f.is_file():
        return []
    rows = []
    for line in f.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            raise ValueError("malformed row in %s: %r" % (f, line))
        rows.append((parts[0].lower(), parts[1], parts[2] if len(parts) > 2 else ""))
    return rows


def render(rows: list[tuple[str, str, str]]) -> str:
    body = "".join("%s  %s  %s\n" % r for r in rows)
    return HEADER + body


def write(repo: pathlib.Path) -> None:
    f = pathlib.Path(repo) / REL
    f.parent.mkdir(parents=True, exist_ok=True)
    data = render(expected(repo)).encode("utf-8")
    f.write_bytes(data)


def check(repo: pathlib.Path) -> list[str]:
    """Every (hash, name) a tag shipped that the file lacks, and every row no tag shipped."""
    want = {(h, n): t for h, n, t in expected(repo)}
    have = {(h, n): t for h, n, t in read_rows(repo)}
    out = ["MISSING  %s  %s  (shipped by %s)" % (h, n, want[(h, n)])
           for (h, n) in want if (h, n) not in have]
    out += ["STRAY    %s  %s  (no release tag shipped this; listed as %s)" % (h, n, have[(h, n)] or "-")
            for (h, n) in have if (h, n) not in want]
    return out


def count_line(rows, n_tags: int) -> str:
    """One count per NAME, every name (FX-B2, delta review: the line named CLAUDE.md and
    AGENTS.md and never .claude/x4-paths.env.example, so its rows were checked and uncounted)."""
    counts = {n: sum(1 for _, rn, _ in rows if rn == n) for n in NAMES}
    return "%d row(s) over %d tags: %s" % (
        sum(counts.values()), n_tags, "; ".join("%d %s" % (counts[n], n) for n in NAMES))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    ap.add_argument("--repo", default=str(pathlib.Path(__file__).resolve().parents[3]))
    a = ap.parse_args(argv)
    repo = pathlib.Path(a.repo)
    try:
        if a.write:
            write(repo)
        rows = expected(repo)
        bad = check(repo)
        n_tags = len(tags(repo))
    except (RuntimeError, ValueError, OSError) as e:
        print("ERROR: %s" % e, file=sys.stderr)
        return 2
    if n_tags == 0:
        print("ERROR: no %s tags in %s -- a shallow clone? Nothing was checked." % (TAG_GLOB, repo),
              file=sys.stderr)
        return 2
    print(count_line(rows, n_tags))
    if bad:
        print("\n".join(bad))
        print("%s is out of date: run gen-shipped-hashes.py --write and commit it." % REL)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
