#!/usr/bin/env python
"""Generate the `x4-cli-reference` skill from every CLI's own argparse help.

WHY THIS EXISTS. The tool inventory was PROSE -- a routing table and README sections
written by hand -- so it drifted from the code and nothing noticed (5 of 11 CLIs were
absent from the routing table on 2026-09-12). Generated from the parsers, the reference
cannot drift: a new flag, subcommand or CLI appears in it the next time this runs, and
`--check` fails the suite until it does.

WHAT IT IS NOT. It is the exact SURFACE of each tool, not the judgement of when to use
which. That stays in CLAUDE.md's routing table, which is in context every turn; this
skill loads on demand. (This is the chosen alternative to an MCP server -- see the
2026-09-09 agent-facing-surface spec, section 7, DEFERRED 2026-09-13.)

HOW TO USE:
    uv run python scripts/gen-cli-reference.py           # regenerate in place
    uv run python scripts/gen-cli-reference.py --check   # rc 1 if stale, missing or ghost

Exit: 0 fresh / written - 1 stale, missing or ghost file(s), named - 2 could not
generate (a partial reference is not written, and not reported as fresh).

TWO MEASURED CHOICES:

* HELP IS CAPTURED IN-PROCESS, never through a subprocess. MEASURED 2026-09-13: a
  subprocess capture MANGLES non-ASCII in `x4validate --help` -- stdout is cp1252 until
  `main()` reconfigures it, and `--help` exits before that line runs -- so the em dash
  arrived as U+FFFD. In-process capture is otherwise byte-identical (53 of 54
  invocations), deterministic run to run, independent of `sys.argv[0]`, and takes
  0.14 s where 54 subprocesses take 10.5 s.
* THE WIDTH IS PINNED (`COLUMNS=100`). argparse wraps help at the terminal width, so an
  unpinned run produces a different file on every machine.

THE SUBCOMMAND SET IS ASKED TWICE AND MUST AGREE. `x4validate._surface.subcommands`
reads argparse's invalid-choice error; this script also parses the `{...}` block of
each CLI's own help. A disagreement REFUSES (rc 2) rather than writing either answer.
"""

from __future__ import annotations

import contextlib
import importlib
import io
import os
import re
import sys
import tomllib
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]          # tools/x4validate
REPO = PKG.parents[1]                              # repository root
SKILL_DIR = REPO / ".claude" / "skills" / "x4-cli-reference"
COLUMNS = "100"

sys.path.insert(0, str(PKG))
from x4validate import _surface  # noqa: E402

BANNER = ("<!-- GENERATED by tools/x4validate/scripts/gen-cli-reference.py from each CLI's "
          "own argparse help. Do not edit: regenerate. -->")

FRONTMATTER = """---
name: x4-cli-reference
description: Use when you need the exact subcommands, flags, positional arguments or defaults of an X4 toolkit CLI (x4validate, x4modlist, x4compat, x4xref, x4stats, x4similar, x4effective, x4diff, x4debug, x4save, x4live), or before composing a command line for one instead of recalling a flag from memory.
---
"""


class GenerationError(Exception):
    """The reference could not be generated faithfully, so nothing is written."""


def entry_points(pkg: Path = PKG) -> dict[str, str]:
    data = tomllib.loads((pkg / "pyproject.toml").read_text(encoding="utf-8"))
    scripts = (data.get("project") or {}).get("scripts") or {}
    if not scripts:
        raise GenerationError(f"[project.scripts] is empty in {pkg / 'pyproject.toml'}")
    return dict(sorted(scripts.items()))


def capture_help(target: str, argv: list[str]) -> str:
    """`main(argv)` of `module:function`, stdout captured, width pinned."""
    modname, func = target.split(":")
    saved_cols = os.environ.get("COLUMNS")
    os.environ["COLUMNS"] = COLUMNS
    buf = io.StringIO()
    try:
        main = getattr(importlib.import_module(modname), func)
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(io.StringIO()):
            main(argv)
    except SystemExit:
        pass                               # silent-ok: argparse exits after printing --help
    finally:
        if saved_cols is None:
            os.environ.pop("COLUMNS", None)
        else:
            os.environ["COLUMNS"] = saved_cols
    text = buf.getvalue()
    if not text.startswith("usage:"):
        raise GenerationError(f"`{target} {' '.join(argv)}` printed no usage block "
                              f"(got {text[:80]!r})")
    if "```" in text:
        raise GenerationError(f"`{target} {' '.join(argv)}` help contains a code fence")
    return text


_BRACES = re.compile(r"^(?P<indent>[ ]*)\{(?P<names>[^}]+)\}[ ]*$", re.M)


def listed_subcommands(top_help: str) -> list[tuple[str, str]]:
    """(name, one-line help) from the `{a,b,c}` block of a top-level help, in order.

    Empty for a single-command CLI. The names come from the braces; the summaries from
    the indented rows argparse prints beneath them, continuation lines joined.
    """
    m = _BRACES.search(top_help)
    if not m:
        return []
    names = [n.strip() for n in m.group("names").split(",") if n.strip()]
    base = len(m.group("indent"))
    summaries: dict[str, str] = {}
    current = None
    for line in top_help[m.end():].splitlines()[1:]:
        if not line.strip():
            break
        indent = len(line) - len(line.lstrip(" "))
        if indent <= base:
            break
        row = re.match(r"^\s+(\S+)(?:\s{2,}(.*))?$", line)
        if row and row.group(1) in names and current != row.group(1) and \
                indent <= base + 4:
            current = row.group(1)
            summaries[current] = (row.group(2) or "").strip()
        elif current is not None:
            # argparse may wrap AT a hyphen ("cross-" / "checked"); rejoin it without a
            # space, or the reference reads "cross- checked".
            sep = "" if summaries[current].endswith("-") else " "
            summaries[current] = (summaries[current] + sep + line.strip()).strip()
    return [(n, summaries.get(n, "")) for n in names]


def description(top_help: str) -> str:
    """The first paragraph after the usage block, whitespace collapsed."""
    paras = re.split(r"\n\s*\n", top_help.strip())
    for p in paras[1:]:
        first = p.strip().splitlines()[0]
        if first.endswith(":") and not first.startswith(" "):
            break                      # reached "positional arguments:" / "options:"
        return " ".join(p.split())
    return ""


def _cell(s: str) -> str:
    return s.replace("|", "\\|")


def generate(pkg: Path = PKG) -> dict[str, str]:
    """{path relative to SKILL_DIR, posix: content}. Raises GenerationError, never partial."""
    eps = entry_points(pkg)
    rows: list[str] = []
    files: dict[str, str] = {}
    for cli, target in eps.items():
        top = capture_help(target, ["--help"])
        listed = listed_subcommands(top)
        asked, note = _surface.subcommands(cli, pkg)
        if asked is None:
            raise GenerationError(f"`{cli}`: surface not enumerable -- {note}")
        if sorted(asked) != sorted(n for n, _ in listed):
            raise GenerationError(
                f"`{cli}`: the two enumerations DISAGREE -- invalid-choice lists "
                f"{sorted(asked)}, --help lists {sorted(n for n, _ in listed)}")
        ref = [BANNER, "", f"# `{cli}`", "", "```text", top.rstrip("\n"), "```", ""]
        rows.append(f"| **`{cli}`** | | {_cell(description(top))} |")
        for sub, summary in listed:
            rows.append(f"| | `{sub}` | {_cell(summary)} |")
            ref += [f"## `{cli} {sub}`", "", "```text",
                    capture_help(target, [sub, "--help"]).rstrip("\n"), "```", ""]
        files[f"reference/{cli}.md"] = "\n".join(ref)
    skill = [FRONTMATTER.rstrip("\n"), "", BANNER, "", "# X4 toolkit CLI reference", "",
             "The exact surface of every toolkit CLI, generated from its own argparse help so "
             "it cannot drift from the code. **Which tool answers which question** is "
             "CLAUDE.md's routing table, not this file.", "",
             "Run a CLI from `tools/x4validate` as `uv run <cli> ...`. The full `--help` of a "
             "CLI and of each of its subcommands is in `reference/<cli>.md` -- read it before "
             "composing a command line.", "",
             f"{len(eps)} CLIs, {sum(1 for r in rows if r.startswith('| | '))} subcommands.", "",
             "| CLI | subcommand | what it does |", "|---|---|---|", *rows, ""]
    files["SKILL.md"] = "\n".join(skill)
    return files


def _norm(b: bytes) -> str:
    return b.decode("utf-8").replace("\r\n", "\n")


def problems(expected: dict[str, str], skill_dir: Path | None = None) -> list[str]:
    """Stale, missing and ghost files. Line endings are normalised: an autocrlf
    checkout of a correct file is not stale.

    `skill_dir` resolves at CALL time. A `= SKILL_DIR` default binds at definition, so
    `main()` kept checking the real directory while a test pointed SKILL_DIR at a
    scratch copy -- one test failed and its twin passed for the wrong reason (found by
    the RED run, 2026-09-13).
    """
    skill_dir = SKILL_DIR if skill_dir is None else skill_dir
    out: list[str] = []
    for rel, text in expected.items():
        p = skill_dir / rel
        if not p.is_file():
            out.append(f"MISSING  {rel}")
        elif _norm(p.read_bytes()) != text:
            out.append(f"STALE    {rel}")
    if skill_dir.is_dir():
        for p in sorted(skill_dir.rglob("*")):
            if p.is_file() and p.relative_to(skill_dir).as_posix() not in expected:
                out.append(f"GHOST    {p.relative_to(skill_dir).as_posix()}")
    return out


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    check = "--check" in argv
    try:
        expected = generate()
    except (GenerationError, _surface.SurfaceUnavailable, OSError) as exc:
        print(f"REFUSING: {exc}", file=sys.stderr)
        return 2
    found = problems(expected)
    if check:
        if found:
            print("x4-cli-reference is out of date -- run scripts/gen-cli-reference.py:",
                  file=sys.stderr)
            for f in found:
                print(f"  {f}", file=sys.stderr)
            return 1
        print(f"x4-cli-reference fresh: {len(expected)} file(s)")
        return 0
    for rel, text in expected.items():
        p = SKILL_DIR / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        data = text.encode("utf-8")        # encode FIRST: a failed encode cannot truncate
        p.write_bytes(data)
    for f in found:
        if f.startswith("GHOST"):
            rel = f.split(None, 1)[1]
            (SKILL_DIR / rel).unlink()
            print(f"  removed ghost {rel}")
    print(f"wrote {len(expected)} file(s) to {SKILL_DIR}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
