#!/usr/bin/env python3
"""Generate every agent-facing file from the neutral source tree in agent/.

    uv run python scripts/gen-agent-trees.py           write the generated files
    uv run python scripts/gen-agent-trees.py --check   0 fresh, 1 stale/missing/ghost, 2 cannot generate

agent/ is the ONLY place to edit. Generated files carry BANNER_MD (markdown) and are committed;
tests/test_gen_agent_trees.py fails when they drift. Modelled on gen-cli-reference.py:
generate() is pure and never returns a partial result. Write mode never deletes: a file in a
generated folder that the generator did not produce is reported as a GHOST and the run refuses.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from ruamel.yaml import YAML

PKG = Path(__file__).resolve().parents[1]
REPO = PKG.parents[1]

BANNER_MD = ("<!-- GENERATED by tools/x4validate/scripts/gen-agent-trees.py from agent/. "
             "Do not edit: regenerate. -->")
# CLAUDE.md is loaded into every session and held under 40,000 characters, so it carries the
# shortest banner that still names the source (plan 1 ruling: the full one pushed it to 40,072).
BANNER_CLAUDE_MD = "<!-- GENERATED from agent/ -->"
TOKEN = "{{TOOLKIT}}"
CLAUDE_TOOLKIT = "$CLAUDE_PROJECT_DIR"
TIER_MODEL = {"fast": "haiku", "balanced": "sonnet", "deep": "opus"}
OWNED: tuple[str, ...] = ("CLAUDE.md", "AGENTS.md", ".claude/agents/", ".claude/skills/",
                          ".claude/settings.json", ".claude/hooks/")
#: Codex silently drops AGENTS.md text past this many BYTES (MEASURED 2026-09-30).
AGENTS_MD_MAX_BYTES = 32768
_IGNORED_PARTS = ("__pycache__",)


class GenerationError(Exception):
    pass


def _read(p: Path) -> str:
    if not p.is_file():
        raise GenerationError(f"missing source file: {p}")
    return p.read_bytes().decode("utf-8").replace("\r\n", "\n")


def _norm(b: bytes) -> str:
    return b.decode("utf-8").replace("\r\n", "\n")


def _with_banner_after_first_line(text: str, banner: str) -> str:
    first, _, rest = text.partition("\n")
    return f"{first}\n\n{banner}\n{rest}"


def _with_banner_after_frontmatter(text: str) -> str:
    if not text.startswith("---\n"):
        raise GenerationError("expected YAML frontmatter at the top")
    end = text.index("\n---\n", 4) + len("\n---\n")
    return f"{text[:end]}\n{BANNER_MD}\n{text[end:]}"


def render_claude_md(src: Path) -> str:
    core = _read(src / "instructions" / "core.md")
    addendum = _read(src / "instructions" / "claude.md")
    out = _with_banner_after_first_line(core, BANNER_CLAUDE_MD)
    return out if not addendum.strip() else out.rstrip("\n") + "\n\n" + addendum


def render_agents_md(src: Path) -> str:
    """AGENTS.md (Codex and other agents). STOPGAP: the Codex addendum alone, until the phase-3
    split brings the shared core under AGENTS_MD_MAX_BYTES. Refuses rather than emitting a
    file Codex would silently truncate."""
    text = _read(src / "instructions" / "codex.md")
    if not text.strip():
        raise GenerationError("agent/instructions/codex.md is empty -- AGENTS.md would say nothing")
    out = _with_banner_after_first_line(text, BANNER_CLAUDE_MD)
    size = len(out.encode("utf-8"))
    if size > AGENTS_MD_MAX_BYTES:
        raise GenerationError(f"AGENTS.md would be {size} bytes; Codex silently drops text past "
                              f"{AGENTS_MD_MAX_BYTES}")
    return out


def render_agent_md(agent_dir: Path) -> tuple[str, str]:
    meta = YAML(typ="safe").load(_read(agent_dir / "agent.yaml"))
    if not isinstance(meta, dict):
        raise GenerationError(f"{agent_dir}/agent.yaml: not a mapping")
    for key in ("name", "description", "tier"):
        if not meta.get(key):
            raise GenerationError(f"{agent_dir}/agent.yaml: missing {key}")
    if meta["tier"] not in TIER_MODEL:
        raise GenerationError(f"{agent_dir}/agent.yaml: unknown tier {meta['tier']!r}")
    tools = (meta.get("claude") or {}).get("tools") or []
    body = _read(agent_dir / "instructions.md").replace(TOKEN, CLAUDE_TOOLKIT)
    lines = ["---", f"name: {meta['name']}", f"description: {meta['description']}"]
    if tools:
        lines.append("tools: " + ", ".join(tools))
    lines += [f"model: {TIER_MODEL[meta['tier']]}", "---", ""]
    text = "\n".join(lines) + "\n" + body
    return f".claude/agents/{meta['name']}.md", _with_banner_after_frontmatter(text)


def render_skills(src: Path) -> dict[str, str]:
    """Every file under agent/skills/<skill>/, TOKEN rendered for Claude. A SKILL.md gets the
    banner after its frontmatter unless it already carries a GENERATED banner of its own
    (x4-cli-reference is generated by gen-cli-reference.py; two banners would be noise)."""
    root = src / "skills"
    skill_dirs = sorted(p for p in root.iterdir() if p.is_dir()) if root.is_dir() else []
    if not skill_dirs:
        raise GenerationError("agent/skills/ holds no skill")
    out: dict[str, str] = {}
    for d in skill_dirs:
        if not (d / "SKILL.md").is_file():
            raise GenerationError(f"{d} has no SKILL.md")
        for f in sorted(d.rglob("*")):
            if not f.is_file() or any(part in _IGNORED_PARTS for part in f.parts):
                continue
            text = _read(f).replace(TOKEN, CLAUDE_TOOLKIT)
            if f.name == "SKILL.md" and "<!-- GENERATED" not in text:
                text = _with_banner_after_frontmatter(text)
            out[".claude/skills/" + f.relative_to(root).as_posix()] = text
    return out


def render_hooks(src: Path) -> dict[str, str]:
    """The guards, copied VERBATIM into .claude/hooks/: no banner (a comment line would move every
    line number the guard tests and mutants anchor on) and no token rewrite (_x4-env.sh uses
    $CLAUDE_PROJECT_DIR as a literal fallback root). Behaviour must not change by a byte."""
    root = src / "guards" / "claude-hooks"
    if not root.is_dir():
        raise GenerationError(f"no guard source at {root}")
    out: dict[str, str] = {}
    for f in sorted(root.rglob("*")):
        if not f.is_file() or any(part in _IGNORED_PARTS + (".pytest_cache",) for part in f.parts):
            continue
        out[".claude/hooks/" + f.relative_to(root).as_posix()] = _read(f)
    if not out:
        raise GenerationError(f"{root} holds no guard")
    return out


def generate(repo: Path) -> dict[str, str]:
    src = repo / "agent"
    if not src.is_dir():
        raise GenerationError(f"no neutral source tree at {src}")
    out: dict[str, str] = {"CLAUDE.md": render_claude_md(src), "AGENTS.md": render_agents_md(src)}
    agents = src / "agents"
    agent_dirs = sorted(p for p in agents.iterdir() if p.is_dir()) if agents.is_dir() else []
    if not agent_dirs:
        raise GenerationError("agent/agents/ holds no agent")
    for d in agent_dirs:
        rel, text = render_agent_md(d)
        out[rel] = text
    out.update(render_skills(src))
    out.update(render_hooks(src))
    out[".claude/settings.json"] = _read(src / "targets" / "claude" / "settings.json")
    return dict(sorted(out.items()))


def _git_visible(root: Path) -> set[str] | None:
    """Tracked + untracked-but-not-ignored files, or None when root is not a git work tree.
    A file .gitignore excludes (.pytest_cache/, __pycache__/) is never a GHOST."""
    try:
        r = subprocess.run(["git", "-C", str(root), "ls-files", "-co", "--exclude-standard", "-z"],
                           capture_output=True, timeout=60)
    except (OSError, subprocess.TimeoutExpired):
        return None
    if r.returncode != 0:
        return None
    return {p for p in r.stdout.decode("utf-8").split("\0") if p}


def _owned_files(root: Path) -> set[str]:
    visible = _git_visible(root)
    found: set[str] = set()
    for prefix in OWNED:
        p = root / prefix
        if prefix.endswith("/"):
            if p.is_dir():
                for f in p.rglob("*"):
                    rel = f.relative_to(root).as_posix()
                    if not f.is_file() or any(part in _IGNORED_PARTS for part in f.parts):
                        continue
                    if visible is None or rel in visible:
                        found.add(rel)
        elif p.is_file():
            found.add(prefix)
    return found


def problems(expected: dict[str, str], root: Path) -> list[str]:
    out: list[str] = []
    for rel, text in expected.items():
        p = root / rel
        if not p.is_file():
            out.append(f"MISSING  {rel}")
        elif _norm(p.read_bytes()) != text:
            out.append(f"STALE    {rel}")
    for rel in sorted(_owned_files(root) - set(expected)):
        out.append(f"GHOST    {rel}")
    return sorted(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    try:
        expected = generate(REPO)
    except GenerationError as e:
        print(f"REFUSING: {e}", file=sys.stderr)
        return 2
    found = problems(expected, REPO)
    if args.check:
        for line in found:
            print(line, file=sys.stderr)
        return 1 if found else 0
    for rel, text in expected.items():
        p = REPO / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        data = text.encode("utf-8")            # encode FIRST: a failed encode cannot truncate
        p.write_bytes(data)
    print(f"wrote {len(expected)} file(s)")
    ghosts = [line for line in found if line.startswith("GHOST")]
    if ghosts:                                 # NEVER delete (user decision 2026-10-01): report and refuse
        for line in ghosts:
            print(line, file=sys.stderr)
        print(f"REFUSING to finish: {len(ghosts)} file(s) in generated folders are not generated. "
              "Move them into agent/ or delete them yourself, then re-run.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
