"""The OpenCode permission config renderer (Plan 3 lane L Task 4): the PRIMARY OpenCode layer,
explicit deny rules rendered per machine from the roots the GUARDS resolve.

What OpenCode feeds its matcher (path.relative(worktree, file), `\\` folded, case-insensitive on
Windows) is READ from its v1.18.34 source; the matcher itself is checked here two ways: a Python
port (oc_match) and OpenCode's OWN match() vendored as fixtures/opencode/wildcard-v1.18.34.mts and
run under node over the same table. Nothing here runs OpenCode (user decision: no local install).
"""
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

PKG = Path(__file__).resolve().parents[1]
REPO = PKG.parents[1]
HOOKS = REPO / ".opencode" / "hooks"
VENDORED = PKG / "tests" / "fixtures" / "opencode" / "wildcard-v1.18.34.mts"
WIN = sys.platform == "win32"
NODE = shutil.which("node")


def oc_match(inp: str, pattern: str, win: bool = WIN) -> bool:
    """A Python port of OpenCode's Wildcard.match (packages/core/src/util/wildcard.ts@v1.18.34)."""
    inp = inp.replace("\\", "/")
    esc = re.sub(r"[.+^${}()|\[\]\\]", lambda m: "\\" + m.group(0), pattern.replace("\\", "/"))
    esc = esc.replace("*", ".*").replace("?", ".")
    if esc.endswith(" .*"):
        esc = esc[:-3] + "( .*)?"
    return re.fullmatch(esc, inp, re.S | (re.I if win else 0)) is not None


def driveless(p) -> str:
    s = str(p).replace("\\", "/")
    return re.sub(r"^[A-Za-z]:", "", s).lstrip("/")


@pytest.fixture
def box(tmp_path):
    """root (an install with the generated .opencode/hooks), a reference OUTSIDE it, game, mods."""
    root = tmp_path / "toolkit"
    shutil.copytree(HOOKS, root / ".opencode" / "hooks",
                    ignore=shutil.ignore_patterns("__pycache__"))
    ref = tmp_path / "X4 data" / "reference"
    game = tmp_path / "Steam" / "X4 Foundations"
    for d in (ref, game / "extensions", tmp_path / "mods", root / "dev"):
        d.mkdir(parents=True)
    env = {k: v for k, v in os.environ.items()
           if not k.startswith("X4_") and k not in ("CLAUDE_PROJECT_DIR", "XRCATTOOL")}
    env.update(X4_CONFIG="/nonexistent", X4_REFERENCE=str(ref), X4_GAME=str(game),
               X4_EXTENSIONS=str(game / "extensions"), X4_MODS=str(tmp_path / "mods"))
    return root, ref, game, env


def run(env, action, root, *extra):
    r = subprocess.run([sys.executable, str(root / ".opencode" / "hooks" / "opencode_config.py"), action,
                        "--root", str(root), *extra], capture_output=True, env=env, timeout=120)
    return r.returncode, r.stdout.decode("utf-8"), r.stderr.decode("utf-8")


def rendered(env, root) -> dict:
    rc, out, err = run(env, "render", root)
    assert rc == 0, err
    first, _, body = out.partition("\n")
    assert first.startswith("// GENERATED by .opencode/hooks/opencode_config.py for ")
    lines = [ln for ln in out.splitlines() if not ln.startswith("//")]
    return json.loads("\n".join(lines))


def denied(perm: dict, key: str, inp: str) -> bool:
    return any(oc_match(inp, pat) for pat, act in perm[key].items() if act == "deny")


def test_rendered_renderer_exists():
    assert (HOOKS / "opencode_config.py").is_file(), "regenerate: uv run python scripts/gen-agent-trees.py"


def _table(ref):
    d = driveless(ref)
    return [  # (input as OpenCode builds it, should_deny)  -- the M1 shapes
        (d + "/a.xml", True),                                   # worktree "/" on Windows: drive-less
        ("../../../" + d + "/l/w.xml", True),                   # a `..` chain out of the worktree
        ((d + "/a.xml").replace("/", "\\"), True),              # backslashes
        ("C:/" + d.upper() + "/A.XML", WIN),                    # other case: Windows only
        (d + "-backup/a.xml", False),
        ("Q:/X4/reference/a.xml", False),
        ("dev/m/libraries/wares.xml", False),
        ("reference/a.xml", False),                             # this reference is NOT in the worktree
    ]


def test_rendered_edit_rules_deny_exactly_the_reference_forms(box):
    root, ref, game, env = box
    perm = rendered(env, root)["permission"]
    got = [(inp, denied(perm, "edit", inp)) for inp, _ in _table(ref)]
    assert got == _table(ref)


def test_cat_dat_denied_only_under_the_four_roots(box):
    root, ref, game, env = box
    perm = rendered(env, root)["permission"]
    g = driveless(game)
    assert denied(perm, "edit", g + "/01.cat") and denied(perm, "edit", g + "/extensions/m/ext_01.dat")
    assert denied(perm, "edit", g + "/extensions/m/ext_01.CAT")
    assert denied(perm, "edit", driveless(root) + "/dist/m/ext_01.cat")       # X4_TOOLKIT (derived)
    assert not denied(perm, "edit", "Users/someone/Documents/OtherGame/save.dat")
    assert not denied(perm, "edit", g + "/readme.txt")
    assert not denied(perm, "edit", g + "/x.catalog")


def test_TWIN_without_X4_GAME_a_game_archive_is_not_in_the_deny_layer(box):
    root, ref, game, env = box
    env = {k: v for k, v in env.items() if k not in ("X4_GAME", "X4_EXTENSIONS")}
    perm = rendered(env, root)["permission"]
    assert not denied(perm, "edit", driveless(game) + "/01.cat")


def test_reference_inside_the_worktree_gets_the_relative_form_too(box):
    root, ref, game, env = box
    inner = root / "reference"
    inner.mkdir()
    r = subprocess.run(["git", "init", "-q", str(root)], capture_output=True)
    assert r.returncode == 0
    perm = rendered(dict(env, X4_REFERENCE=str(inner)), root)["permission"]
    assert denied(perm, "edit", "reference/a.xml")
    assert denied(perm, "edit", "reference\\libraries\\wares.xml")
    assert not denied(perm, "edit", "dev/myreference/a.xml")
    assert not denied(perm, "edit", "reference-backup/a.xml")
    assert denied(perm, "edit", "dist/m/ext_01.cat")                 # toolkit == worktree: everything in it


def test_TWIN_outside_a_git_repo_there_is_no_relative_form(box):
    root, ref, game, env = box
    inner = root / "reference"
    inner.mkdir()
    perm = rendered(dict(env, X4_REFERENCE=str(inner), GIT_CEILING_DIRECTORIES=str(root.parent)), root)["permission"]
    assert not any(not p.startswith("*") for p in perm["edit"]), perm["edit"]


@pytest.mark.parametrize("cmd,deny", [
    ("rm -rf {ref}/libraries", True),
    ("rm -rf {ref}", True),
    ("rm -rf '{ref}'", True),
    ('rm -rf "{ref}/x" other', True),
    ("Remove-Item -Recurse -Force {refw}\\libraries", True),
    ("mv {ref}/a.xml dev/", True),
    ("cp {ref}/a.xml dev/", False),
    ("cat {ref}/a.xml", False),
    ("grep -r ware {ref}/libraries", False),
    ("rm -rf dev/x", False),
    ("rm -rf {ref}-backup", False),
])
def test_bash_deletion_verbs_deny_and_read_verbs_do_not(box, cmd, deny):
    root, ref, game, env = box
    perm = rendered(env, root)["permission"]
    c = cmd.format(ref=str(ref).replace("\\", "/"), refw=str(ref).replace("/", "\\"))
    assert denied(perm, "bash", c) == deny, (c, deny)


def test_no_allow_rule_and_no_catch_all_is_ever_emitted(box):
    root, ref, game, env = box
    cfg = rendered(env, root)
    for key, rules in cfg["permission"].items():
        assert isinstance(rules, dict) and rules, key
        assert set(rules.values()) == {"deny"}, key
        assert "*" not in rules, key
    assert cfg["instructions"] == [".opencode/X4-OPENCODE.md"]


def test_roots_come_from_the_guards_loader_not_a_second_parser(box):
    root, ref, game, env = box
    other = ref.parent / "other-ref"
    other.mkdir()
    cfgfile = root / "x4-paths.env"
    cfgfile.write_bytes(f'X4_REFERENCE="{other.as_posix()}"\n'.encode("utf-8"))   # quoted: a space
    # exported X4_REFERENCE beats the config file, exactly as in _x4-env.sh
    perm = rendered(dict(env, X4_CONFIG=str(cfgfile)), root)["permission"]
    assert denied(perm, "edit", driveless(ref) + "/a.xml")
    assert not denied(perm, "edit", driveless(other) + "/a.xml")


def test_TWIN_the_config_file_decides_when_nothing_is_exported(box):
    root, ref, game, env = box
    other = ref.parent / "other-ref"
    other.mkdir()
    cfgfile = root / "x4-paths.env"
    cfgfile.write_bytes(f'X4_REFERENCE="{other.as_posix()}"\n'.encode("utf-8"))   # quoted: a space
    env ={k: v for k, v in env.items() if k != "X4_REFERENCE"}
    perm = rendered(dict(env, X4_CONFIG=str(cfgfile)), root)["permission"]
    assert denied(perm, "edit", driveless(other) + "/a.xml")


@pytest.mark.parametrize("bad", ["refer*nce", "ref?"])
def test_a_wildcard_in_a_root_REFUSES(box, bad):
    root, ref, game, env = box
    rc, out, err = run(dict(env, X4_REFERENCE=str(ref.parent / bad)), "write", root)
    assert rc == 2 and "wildcard" in err and not (root / ".opencode" / "opencode.jsonc").exists()


def test_a_missing_loader_REFUSES(box):
    root, ref, game, env = box
    (root / ".opencode" / "hooks" / "_x4-env.sh").unlink()
    rc, out, err = run(env, "write", root)
    assert rc == 2 and "_x4-env.sh" in err and not (root / ".opencode" / "opencode.jsonc").exists()


def test_no_bash_REFUSES(box, tmp_path):
    root, ref, game, env = box
    rc, out, err = run(dict(env, X4_BASH=str(tmp_path / "no-bash.exe")), "write", root)
    assert rc == 2 and not (root / ".opencode" / "opencode.jsonc").exists()


def test_write_then_check_is_fresh_and_rewrite_is_allowed(box):
    root, ref, game, env = box
    assert run(env, "write", root)[0] == 0
    assert run(env, "check", root)[0] == 0
    assert run(env, "write", root)[0] == 0          # our own banner: overwritten


def test_write_never_overwrites_a_file_without_our_banner(box):
    root, ref, game, env = box
    mine = root / ".opencode" / "opencode.jsonc"
    mine.write_text('{"permission": {"edit": "ask"}}\n', encoding="utf-8")
    rc, out, err = run(env, "write", root)
    assert rc == 3 and "not ours" in err
    assert mine.read_text(encoding="utf-8") == '{"permission": {"edit": "ask"}}\n'


def test_check_reports_missing_then_stale_after_the_reference_moves(box):
    root, ref, game, env = box
    assert run(env, "check", root)[0] == 1
    assert run(env, "write", root)[0] == 0
    moved = ref.parent / "moved-ref"
    moved.mkdir()
    assert run(dict(env, X4_REFERENCE=str(moved)), "check", root)[0] == 1


def test_check_cannot_render_is_rc_2(box):
    root, ref, game, env = box
    assert run(dict(env, X4_REFERENCE=str(ref.parent / "a*b")), "check", root)[0] == 2


def _node_cmd():
    v = subprocess.run([NODE, "--version"], capture_output=True, text=True).stdout.strip().lstrip("v")
    major, minor = (int(x) for x in v.split(".")[:2])
    strip = [] if (major, minor) >= (23, 6) else ["--experimental-strip-types"]
    return [NODE, "--no-warnings", *strip]


def test_the_python_matcher_agrees_with_opencodes_own(box, tmp_path):
    if not NODE:
        if os.environ.get("CI"):
            pytest.fail("node is required on CI to check the rules against OpenCode's own matcher")
        pytest.skip("node not installed -- the Python matcher NOT cross-checked against OpenCode's")
    root, ref, game, env = box
    perm = rendered(env, root)["permission"]
    inputs = [i for i, _ in _table(ref)] + [
        "rm -rf " + str(ref).replace("\\", "/") + "/x", "cp " + str(ref) + "/x dev/",
        "Remove-Item -Recurse " + str(ref).replace("/", "\\") + "\\x", "ls", "rm -rf '" + str(ref) + "'"]
    cases = [[i, p] for i in inputs for p in list(perm["edit"]) + list(perm["bash"])]
    cases += [["ls -la", "ls *"], ["ls", "ls *"], ["a.b", "a?b"], ["axb", "a.b"], ["(x)", "(*)"], ["A", "a"]]
    (tmp_path / "cases.json").write_text(json.dumps(cases), encoding="utf-8")
    driver = tmp_path / "drive.mjs"
    driver.write_text(
        "import { readFileSync } from 'node:fs';\n"
        f"import {{ match }} from {json.dumps(VENDORED.as_uri())};\n"
        "const cases = JSON.parse(readFileSync(process.argv[2], 'utf8'));\n"
        "process.stdout.write(JSON.stringify(cases.map(([i, p]) => match(i, p))));\n", encoding="utf-8")
    r = subprocess.run([*_node_cmd(), str(driver), str(tmp_path / "cases.json")], capture_output=True, timeout=120)
    assert r.returncode == 0, r.stderr.decode("utf-8", "replace")
    theirs = json.loads(r.stdout)
    ours = [oc_match(i, p) for i, p in cases]
    diff = [(c, a, b) for c, a, b in zip(cases, ours, theirs) if a != b]
    assert diff == [] and len(theirs) == len(cases) and any(theirs) and not all(theirs)


def test_the_rendered_config_is_never_committed():
    """It names this machine's absolute roots: rendered at install, git-ignored."""
    r = subprocess.run(["git", "-C", str(REPO), "check-ignore", "-q", ".opencode/opencode.jsonc"])
    assert r.returncode == 0, ".opencode/opencode.jsonc must be git-ignored"
