"""The OpenCode plugin (Plan 3 lane L Task 5): .opencode/plugins/x4guard.js is TRANSPORT only --
find Python, run .opencode/hooks/opencode_adapter.py with a bound, accept ONE `X4OK {...}` line,
throw on deny -- and fails CLOSED on everything it controls.

Driven under node (fixtures/opencode/drive-plugin.mjs). OpenCode runs plugins under Bun, and
whether OpenCode honours the throw is READ from its docs and source, never run here (user
decision: no local install). node is required on CI; off CI its absence is a counted skip.
"""
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import pytest

from codex_testlib import REPO, make_sandbox

PKG = REPO / "tools" / "x4validate"
DRIVER = PKG / "tests" / "fixtures" / "opencode" / "drive-plugin.mjs"
PLUGIN = REPO / ".opencode" / "plugins" / "x4guard.js"
NODE = shutil.which("node")
WIN = sys.platform == "win32"


@pytest.fixture(autouse=True)
def _node():
    if not NODE:
        if os.environ.get("CI"):
            pytest.fail("node is required on CI for the OpenCode plugin tests")
        pytest.skip("node not installed -- OpenCode plugin transport NOT checked here")


@pytest.fixture
def oc(tmp_path):
    """(tk, env): a sandbox toolkit with the generated .opencode/ copied in."""
    tmp, tk, env = make_sandbox(tmp_path)
    for sub in ("hooks", "plugins"):
        shutil.copytree(REPO / ".opencode" / sub, tk / ".opencode" / sub,
                        ignore=shutil.ignore_patterns("__pycache__"))
    env = dict(env, X4_PYTHON=sys.executable, X4_OPENCODE_SHELL="bash")
    return tk, env


def drive(tk, env, steps, timeout=180):
    case = {"ctx": {"directory": str(tk), "worktree": str(tk)}, "steps": steps}
    cf = tk / "case.json"
    cf.write_text(json.dumps(case), encoding="utf-8")
    r = subprocess.run([NODE, str(DRIVER), str(tk / ".opencode" / "plugins" / "x4guard.js"), str(cf)],
                       capture_output=True, env=env, timeout=timeout)
    assert r.returncode == 0, r.stderr.decode("utf-8", "replace")
    return json.loads(r.stdout.decode("utf-8").strip().splitlines()[-1])


def before(tool, args, call="c1"):
    return {"hook": "tool.execute.before", "input": {"tool": tool, "sessionID": "s", "callID": call},
            "output": {"args": args}}


def after(tool, args, call="c1", out="done"):
    return {"hook": "tool.execute.after", "input": {"tool": tool, "sessionID": "s", "callID": call, "args": args},
            "output": {"title": "", "output": out, "metadata": {}}}


def test_the_generated_plugin_exists_with_a_banner():
    assert PLUGIN.is_file(), "regenerate: uv run python scripts/gen-agent-trees.py"
    assert PLUGIN.read_text(encoding="utf-8").startswith("// GENERATED by tools/x4validate/scripts/gen-agent-trees.py")


def test_the_plugin_module_has_exactly_one_export(oc):
    tk, env = oc
    r = drive(tk, env, [])
    assert r["exports"] == ["X4Guard"], r


def test_a_reference_edit_THROWS_with_the_guard_reason(oc):
    tk, env = oc
    r = drive(tk, env, [before("edit", {"filePath": str(tk / "reference" / "libraries" / "wares.xml"),
                                       "oldString": "ref", "newString": "x"})])
    s = r["steps"][0]
    assert s["threw"] and "reference" in s["message"] and "INERT" not in s["message"], s


def test_TWIN_a_dev_edit_does_not_throw(oc):
    tk, env = oc
    (tk / "dev" / "mymod" / "a.xml").write_text("a\n", encoding="utf-8")
    r = drive(tk, env, [before("edit", {"filePath": "dev/mymod/a.xml", "oldString": "a", "newString": "b"})])
    assert not r["steps"][0]["threw"], r


def test_a_bash_delete_of_reference_THROWS(oc):
    tk, env = oc
    r = drive(tk, env, [before("bash", {"command": "rm -rf reference/libraries"})])
    assert r["steps"][0]["threw"], r


def test_a_read_tool_never_spawns_python(oc, tmp_path):
    tk, env = oc
    env = dict(env, X4_PYTHON=str(tmp_path / "no-python.exe"), X4_NO_PYTHON_FALLBACK="1")
    r = drive(tk, env, [before(t, {"filePath": str(tk / "reference" / "x")}) for t in ("read", "glob", "grep", "webfetch")])
    assert not any(s["threw"] for s in r["steps"]), r


def test_no_python_THROWS_inert(oc, tmp_path):
    tk, env = oc
    env = dict(env, X4_PYTHON=str(tmp_path / "no-python.exe"), X4_NO_PYTHON_FALLBACK="1")
    r = drive(tk, env, [before("edit", {"filePath": "dev/mymod/a.xml", "oldString": "a", "newString": "b"})])
    s = r["steps"][0]
    assert s["threw"] and s["message"].startswith("X4 GUARD INERT") and "Python" in s["message"], s


def test_a_missing_adapter_THROWS_inert(oc):
    tk, env = oc
    (tk / ".opencode" / "hooks" / "opencode_adapter.py").unlink()
    r = drive(tk, env, [before("write", {"filePath": "dev/mymod/n.xml", "content": ""})])
    s = r["steps"][0]
    assert s["threw"] and s["message"].startswith("X4 GUARD INERT"), s


def test_an_unknown_shell_reaches_the_adapter_and_THROWS_inert(oc):
    tk, env = oc
    r = drive(tk, dict(env, X4_OPENCODE_SHELL="cmd"), [before("bash", {"command": "echo hi"})])
    s = r["steps"][0]
    assert s["threw"] and "INERT" in s["message"], s


STUBS = {
    "garbage": "print('hello')",
    "two_lines": "print('X4OK {\"v\":1,\"decision\":\"allow\",\"inert\":false,\"reason\":null,\"context\":null}')\n"
                 "print('X4OK {\"v\":1,\"decision\":\"allow\",\"inert\":false,\"reason\":null,\"context\":null}')",
    "crash": "raise RuntimeError('boom')",
    "unknown_decision": "print('X4OK {\"v\":1,\"decision\":\"maybe\",\"inert\":false,\"reason\":null,\"context\":null}')",
    "empty": "pass",
    "not_an_object": "print('X4OK [1]')",
    "deny_without_reason": "print('X4OK {\"v\":1,\"decision\":\"deny\",\"inert\":false,\"reason\":null,\"context\":null}')",
}


@pytest.mark.parametrize("stub", sorted(STUBS))
def test_any_adapter_failure_THROWS(oc, stub):
    tk, env = oc
    (tk / ".opencode" / "hooks" / "opencode_adapter.py").write_text("import sys\nsys.stdin.read()\n" + STUBS[stub] + "\n",
                                                                   encoding="utf-8")
    r = drive(tk, env, [before("edit", {"filePath": "dev/mymod/a.xml", "oldString": "a", "newString": "b"})])
    s = r["steps"][0]
    assert s["threw"] and s["message"].startswith("X4 GUARD"), s


def _alive(pid: int) -> bool:
    if WIN:
        r = subprocess.run(["tasklist", "/FI", f"PID eq {pid}", "/NH"], capture_output=True, text=True)
        return str(pid) in r.stdout
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def test_a_hung_adapter_is_killed_with_its_children_and_THROWS_inert(oc, tmp_path):
    tk, env = oc
    pidfile = tmp_path / "grandchild.pid"
    stub = ("import subprocess, sys, time\n"
            "sys.stdin.read()\n"
            "p = subprocess.Popen([sys.executable, '-c', 'import time; time.sleep(120)'])\n"
            f"open({str(pidfile)!r}, 'w').write(str(p.pid))\n"
            "time.sleep(120)\n")
    (tk / ".opencode" / "hooks" / "opencode_adapter.py").write_text(stub, encoding="utf-8")
    t0 = time.monotonic()
    r = drive(tk, dict(env, X4_OPENCODE_TIMEOUT_S="3"),
              [before("edit", {"filePath": "dev/mymod/a.xml", "oldString": "a", "newString": "b"})])
    took = time.monotonic() - t0
    s = r["steps"][0]
    assert s["threw"] and s["message"].startswith("X4 GUARD INERT") and "timed out" in s["message"], s
    assert took < 3 + 10, f"a 3 s bound took {took:.1f} s"
    pid = int(pidfile.read_text())
    deadline = time.monotonic() + 10
    while _alive(pid) and time.monotonic() < deadline:
        time.sleep(0.3)
    assert not _alive(pid), "the adapter's child survived the timeout: the process TREE was not killed"


@pytest.mark.parametrize("bad", ["0", "-1", "abc"])
def test_a_bad_timeout_setting_THROWS_inert(oc, bad):
    tk, env = oc
    r = drive(tk, dict(env, X4_OPENCODE_TIMEOUT_S=bad),
              [before("edit", {"filePath": "dev/mymod/a.xml", "oldString": "a", "newString": "b"})])
    s = r["steps"][0]
    assert s["threw"] and "X4_OPENCODE_TIMEOUT_S" in s["message"], s


def test_an_advise_reaches_the_tool_output_after(oc):
    tk, env = oc
    args = {"filePath": "dev/mymod/content.xml", "oldString": "a", "newString": "b"}
    (tk / "dev" / "mymod" / "content.xml").write_text("<content/>\n", encoding="utf-8")
    r = drive(tk, env, [before("edit", args), after("edit", args)])
    b, a = r["steps"]
    assert not b["threw"] and not a["threw"], r
    assert a["output"]["output"].startswith("done\n\n[X4 guards] "), a


def test_TWIN_a_plain_allow_leaves_the_tool_output_alone(oc):
    tk, env = oc
    args = {"filePath": "dev/mymod/a.txt", "content": "x"}
    r = drive(tk, env, [before("write", args), after("write", args)])
    assert r["steps"][1]["output"]["output"] == "done", r


def test_after_never_throws_even_when_python_is_gone(oc, tmp_path):
    tk, env = oc
    env = dict(env, X4_PYTHON=str(tmp_path / "no-python.exe"), X4_NO_PYTHON_FALLBACK="1")
    r = drive(tk, env, [after("edit", {"filePath": "dev/mymod/a.xml"})])
    s = r["steps"][0]
    assert not s["threw"] and "DID NOT RUN" in s["output"]["output"], s


def test_the_banner_is_added_to_the_system_prompt(oc):
    tk, env = oc
    r = drive(tk, env, [{"hook": "experimental.chat.system.transform", "input": {"model": {}},
                         "output": {"system": ["base"]}}])
    s = r["steps"][0]
    assert not s["threw"] and s["output"]["system"][0] == "base"
    assert s["output"]["system"][1].startswith("X4 GUARDS LIVE (opencode plugin v1)")
