// GENERATED by tools/x4validate/scripts/gen-agent-trees.py from agent/targets/opencode/x4guard.js. Do not edit: regenerate.
// X4 toolkit guard plugin for the OpenCode CLI -- TRANSPORT ONLY. It decides nothing: it hands each
// bash / edit / write / apply_patch call to ../hooks/opencode_adapter.py (the toolkit's guards) and
// THROWS when they refuse, which is how an OpenCode plugin blocks a tool call (READ
// opencode.ai/docs/plugins). BEST EFFORT, from OpenCode's docs and source (v1.18.34), NOT measured
// against a running OpenCode. The OpenCode DESKTOP APP is NOT supported: its plugin hooks never
// fire (anomalyco/opencode#38604, closed as not planned).
//
// Fails CLOSED on everything it controls -- no Python, a missing adapter, a crash, a timeout, any
// output other than ONE `X4OK {...}` line -- by throwing `X4 GUARD INERT: ...`. What it cannot
// control: OpenCode SKIPS a plugin that fails to load with only a log line (READ plugin/index.ts),
// so the system-prompt line `X4 GUARDS LIVE` is the only sign it loaded.
//
// Exactly ONE export: OpenCode calls EVERY export of a plugin module as a plugin (READ).
// Settings (environment): X4_PYTHON (+ X4_NO_PYTHON_FALLBACK=1), X4_OPENCODE_SHELL (bash or
// powershell: overrides the shell the plugin derives from OpenCode's `shell` config and $SHELL),
// X4_OPENCODE_TIMEOUT_S (default 60; the adapter's own budget is 45).
import { spawn, spawnSync } from "node:child_process"
import { existsSync } from "node:fs"
import { fileURLToPath } from "node:url"

// Every BUILT-IN OpenCode tool that writes a file or runs a command (R7-13, READ at v1.18.34:
// tool/registry.ts registers shell(bash), read, glob, grep, edit, write, task, webfetch, todowrite,
// websearch, skill, apply_patch, question, lsp (9 read-only queries), plan_exit and, when enabled,
// code-mode `execute`, which calls MCP tools only). NOT judged, and disclosed: MCP tools (also
// through `execute`), custom tools from `.opencode/tool(s)/*.{js,ts}` and plugin-defined tools.
// Recorded in docs/superpowers/measurements/2026-10-02-opencode-read.md (R15).
const JUDGED = new Set(["bash", "edit", "write", "apply_patch"])
const WRITES = new Set(["edit", "write", "apply_patch"])
const DECISIONS = new Set(["allow", "advise", "deny"])
const BANNER =
  "X4 GUARDS LIVE (opencode plugin v1) -- every bash, edit, write and apply_patch is checked. " +
  "If you do not see this line, the plugin did not load."
const MAX_OUT = 1 << 20
const WIN = process.platform === "win32"

function inertError(cause) {
  const e = new Error(`X4 GUARD INERT: ${cause}. NOTHING was checked; this is a refusal, not a verdict.`)
  e.x4inert = true
  return e
}

function timeoutSeconds() {
  const raw = process.env.X4_OPENCODE_TIMEOUT_S
  if (raw === undefined || raw.trim() === "") return 60
  const t = Number(raw)
  if (!Number.isFinite(t) || t <= 0) throw inertError(`X4_OPENCODE_TIMEOUT_S=${JSON.stringify(raw)} is not a positive number of seconds`)
  return t
}

// The grammar the guards judge a `bash` call in must be the grammar of the shell OpenCode RUNS it in
// (FX-G3, v4.0.0 delta review). This mirrors OpenCode's own choice (READ packages/core/src/shell.ts,
// acceptable(), at f2cf607): its configured `shell`, else $SHELL -- either one only if acceptable
// (fish and nu are refused) -- else the platform default: on Windows pwsh, powershell, Git Bash,
// %COMSPEC% in that order; elsewhere zsh (macOS) or bash or sh. The old version said "bash" for EVERY
// shell off Windows (so a pwsh user's `Remove-Item -Recurse` was judged as bash: allow, where the
// PowerShell grammar denies -- MEASURED with x4guard check), ignored the configured shell, and
// called sh, zsh and cmd "powershell". A shell the guards have no grammar for (cmd, ...) is passed
// through by name: the adapter refuses it, so the call is INERT (refused), never judged wrongly.
const POSIX_SHELLS = new Set(["bash", "dash", "ksh", "sh", "zsh"])
const PS_SHELLS = new Set(["pwsh", "powershell"])
const REFUSED_BY_OPENCODE = new Set(["fish", "nu"])
let configShell = null

function shellBaseName(file) {
  const base = String(file).split(/[\\/]/).pop().toLowerCase()
  return WIN ? base.replace(/\.[^.]*$/, "") : base
}

function grammarOf(name) {
  if (POSIX_SHELLS.has(name)) return "bash"
  if (PS_SHELLS.has(name)) return "powershell"
  return name // no guard grammar: the adapter refuses it (inert)
}

function shellName() {
  if (process.env.X4_OPENCODE_SHELL) return process.env.X4_OPENCODE_SHELL
  // OpenCode consults ONE source: the configured shell when set (falling back to the platform default,
  // NOT to $SHELL, when it is refused), else $SHELL.
  const chosen = configShell || process.env.SHELL || ""
  const name = chosen ? shellBaseName(chosen) : ""
  if (name && !REFUSED_BY_OPENCODE.has(name)) return grammarOf(name)
  return WIN ? "powershell" : "bash"
}

let pythonCache = null
function findPython() {
  if (pythonCache) return pythonCache
  const cands = []
  if (process.env.X4_PYTHON) cands.push([process.env.X4_PYTHON])
  if (process.env.X4_NO_PYTHON_FALLBACK !== "1") {
    if (WIN) cands.push(["py", "-3"])
    cands.push(["python3"], ["python"])
  }
  for (const c of cands) {
    const r = spawnSync(c[0], [...c.slice(1), "-c", "import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)"], {
      stdio: "ignore",
      timeout: 15000,
      windowsHide: true,
    })
    if (!r.error && r.status === 0) {
      pythonCache = c
      return c
    }
  }
  return null
}

function killTree(child) {
  try {
    if (WIN) spawnSync("taskkill", ["/F", "/T", "/PID", String(child.pid)], { stdio: "ignore", windowsHide: true, timeout: 15000 })
    else process.kill(-child.pid, "SIGKILL")
  } catch {
    try { child.kill("SIGKILL") } catch {}
  }
}

function parse(text) {
  const lines = text.split(/\r?\n/).filter((l) => l.trim() !== "")
  if (lines.length !== 1 || !lines[0].startsWith("X4OK ")) {
    throw inertError(`the guard adapter answered ${lines.length} line(s) without one X4OK verdict`)
  }
  let v
  try {
    v = JSON.parse(lines[0].slice(5))
  } catch {
    throw inertError("the guard adapter's verdict is not JSON")
  }
  if (!v || typeof v !== "object" || Array.isArray(v) || !DECISIONS.has(v.decision)) {
    throw inertError("the guard adapter's verdict names no known decision")
  }
  return v
}

function runAdapter(adapter, event, payload) {
  const limit = timeoutSeconds()
  const py = findPython()
  if (!py) throw inertError("no Python >= 3.10 found for the guards (set X4_PYTHON)")
  if (!existsSync(adapter)) throw inertError(`the guard adapter is missing: ${adapter}`)
  return new Promise((resolve, reject) => {
    let out = ""
    let done = false
    const finish = (fn, arg) => {
      if (done) return
      done = true
      clearTimeout(timer)
      fn(arg)
    }
    let child
    try {
      child = spawn(py[0], [...py.slice(1), adapter, event], {
        stdio: ["pipe", "pipe", "ignore"],
        windowsHide: true,
        detached: !WIN, // its own process group, so a timeout can kill the whole tree
      })
    } catch (e) {
      throw inertError(`the guard adapter could not start (${e && e.code ? e.code : e})`)
    }
    const timer = setTimeout(() => {
      killTree(child)
      finish(reject, inertError(`the guard adapter timed out after ${limit} s (X4_OPENCODE_TIMEOUT_S)`))
    }, limit * 1000)
    child.on("error", (e) => finish(reject, inertError(`the guard adapter could not run (${e && e.code ? e.code : e})`)))
    child.stdout.on("data", (b) => {
      out += b.toString("utf8")
      if (out.length > MAX_OUT) {
        killTree(child)
        finish(reject, inertError("the guard adapter's output is over 1 MB"))
      }
    })
    child.on("close", (code) => {
      if (code !== 0) return finish(reject, inertError(`the guard adapter exited ${code}`))
      try {
        finish(resolve, parse(out))
      } catch (e) {
        finish(reject, e)
      }
    })
    child.stdin.on("error", () => {}) // a child that exits early: its exit code decides
    child.stdin.end(JSON.stringify(payload))
  })
}

export const X4Guard = async ({ directory }) => {
  const adapter = fileURLToPath(new URL("../hooks/opencode_adapter.py", import.meta.url))
  const advisories = new Map()
  const ask = (event, tool, args) =>
    runAdapter(adapter, event, { v: 1, tool, args: args ?? {}, directory, shell: shellName() })

  return {
    // OpenCode hands every plugin its config at load (READ plugin/index.ts: hook.config?.(cfg)); its
    // `shell` decides which shell runs a `bash` call, so it decides the grammar it is judged in.
    config: async (cfg) => {
      configShell = cfg && typeof cfg.shell === "string" && cfg.shell.trim() ? cfg.shell.trim() : null
    },

    "tool.execute.before": async (input, output) => {
      if (!JUDGED.has(input.tool)) return
      let v
      try {
        v = await ask("pre", input.tool, output.args)
      } catch (e) {
        throw e && e.x4inert ? e : inertError(`the plugin failed (${e && e.message ? e.message : e})`)
      }
      if (v.decision === "deny") throw new Error(v.reason || "X4 GUARD: refused, with no reason given")
      if (v.decision === "advise" && v.context) advisories.set(input.callID, v.context)
    },

    "tool.execute.after": async (input, output) => {
      const notes = []
      const pre = advisories.get(input.callID)
      advisories.delete(input.callID)
      if (pre) notes.push(pre)
      if (WRITES.has(input.tool)) {
        try {
          const v = await ask("post", input.tool, input.args)
          if (v.decision === "advise" && v.context) notes.push(v.context)
        } catch (e) {
          notes.push(`X4 VALIDATION DID NOT RUN: ${e && e.message ? e.message : e}`)
        }
      }
      if (notes.length && output && typeof output.output === "string") {
        output.output += "\n\n[X4 guards] " + notes.join("\n\n")
      }
    },

    "experimental.chat.system.transform": async (_input, output) => {
      if (output && Array.isArray(output.system)) output.system.push(BANNER)
    },
  }
}
