#!/usr/bin/env python3
"""Render the per-machine OpenCode permission config (.opencode/opencode.jsonc): the PRIMARY
OpenCode guard layer, explicit `deny` rules that OpenCode itself enforces with no plugin.

    python .opencode/hooks/opencode_config.py render --root R   print the JSONC
    python .opencode/hooks/opencode_config.py write  --root R   write R/.opencode/opencode.jsonc
    python .opencode/hooks/opencode_config.py check  --root R   0 fresh, 1 stale or missing, 2 cannot render

`write` never overwrites a file whose first line is not our banner (rc 3): that file is the
user's. Nothing is written when rendering fails (rc 2).

The roots are the ones the GUARDS resolve: R/.opencode/hooks/_x4-env.sh is SOURCED under the
guards' own bash, with HOOK_DIR set and the caller's environment (CLAUDE_PROJECT_DIR removed:
OpenCode never sets it), so env var > x4-paths.env > default exactly as for every guard. There is
no second parser of the config here, by design.

What is emitted (BEST EFFORT: READ from OpenCode v1.18.34 docs and source, and the pattern forms
MEASURED against OpenCode's own matcher under node; never run inside OpenCode):
  - OpenCode matches an edit/write/apply_patch path as `path.relative(worktree, file)` (worktree =
    the git top level, else "/"), with `\\` folded to `/`, `*`/`?` wildcards, anchored, and
    case-insensitive on Windows. So each root P gets `*<P without drive or leading slash>/...`
    (matches the drive-less, `..`-chain and other-case forms) plus, when P is inside the
    worktree, the worktree-relative form.
  - permission.edit: everything under X4_REFERENCE; `.cat`/`.dat` under X4_GAME, X4_EXTENSIONS,
    X4_MODS and X4_TOOLKIT (protect-files.sh's scope). All "deny".
  - permission.bash: DELETION verbs aimed at X4_REFERENCE by absolute path, "deny". Never a
    read verb: copying out of reference/ is legitimate.
  - NO "*" key and NO allow rule: an allow would loosen the user's own stricter config.
  - The game-install block is NOT here: the guard allows a whitelist inside the game folder,
    which only allow rules could express. The plugin layer carries it.
Stdlib only; Python >= 3.10.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
for _p in (HERE, HERE.parent / "claude-hooks"):         # rendered tree, then the source tree
    if (_p / "x4guard.py").is_file() and str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import x4guard                     # noqa: E402  (sibling module; path set above)

CONFIG_REL = ".opencode/opencode.jsonc"
BANNER_PREFIX = "// GENERATED by .opencode/hooks/opencode_config.py"
ADDENDUM = ".opencode/X4-OPENCODE.md"
SCHEMA = "https://opencode.ai/config.json"
ROOT_KEYS = ("X4_REFERENCE", "X4_GAME", "X4_EXTENSIONS", "X4_MODS", "X4_TOOLKIT")
ARCHIVE_ROOTS = ("X4_GAME", "X4_EXTENSIONS", "X4_MODS", "X4_TOOLKIT")
#: Upper case too: OpenCode matches case-SENSITIVELY off Windows (READ wildcard.ts).
ARCHIVE_EXTS = (".cat", ".dat", ".CAT", ".DAT")
DELETE_VERBS = ("rm", "rmdir", "unlink", "shred", "del", "erase", "rd", "Remove-Item", "ri",
                "mv", "move", "Move-Item", "mi", "ren", "Rename-Item")
_MSYS = re.compile(r"^/([A-Za-z])(?:/|$)")


class RenderError(Exception):
    pass


def oc_posix(p: str) -> str:
    """P with `/` separators, a Git Bash `/c/...` read as `C:/...` on Windows, no trailing `/`."""
    s = p.replace("\\", "/")
    if sys.platform == "win32":
        s = _MSYS.sub(lambda m: m.group(1).upper() + ":/", s)
    return s.rstrip("/") or s


def oc_driveless(p: str) -> str:
    """The tail OpenCode's input always ends with: no drive letter, no leading `/`."""
    return re.sub(r"^[A-Za-z]:", "", oc_posix(p)).lstrip("/")


def resolve_roots(root: Path) -> dict[str, str]:
    """The roots as the guards see them, by sourcing the guards' own loader."""
    hooks = root / ".opencode" / "hooks"
    if not (hooks / "_x4-env.sh").is_file():
        raise RenderError(f"{hooks / '_x4-env.sh'} is missing, so the guards' roots cannot be resolved")
    bash, why = x4guard.resolve_bash()
    if not bash:
        raise RenderError(f"no usable bash: {why}")
    # cygpath -m (Git Bash, MSYS2, Cygwin only): a root bash derived with `pwd` is a MOUNT path
    # there (MEASURED: the Windows temp folder reads `/tmp/...`), which OpenCode never sees.
    # Each root is printed RAW and converted: cygpath silently DROPS a `*` (MEASURED `b*c` ->
    # `bc`), so the wildcard refusal must look at the raw value.
    script = ('HOOK_DIR="$1"; . "$1/_x4-env.sh" >/dev/null 2>&1 || exit 3; '
              'for _v in ' + " ".join(f'"${{{k}:-}}"' for k in ROOT_KEYS) + '; do _c="$_v"; '
              'if [ -n "$_v" ] && command -v cygpath >/dev/null 2>&1; then _c="$(cygpath -m "$_v")" || exit 4; fi; '
              'printf "%s\\0%s\\0" "$_v" "$_c"; done')
    env = {k: v for k, v in os.environ.items() if k != "CLAUDE_PROJECT_DIR"}
    try:
        r = subprocess.run([bash, "-c", script, "x4", hooks.as_posix()], capture_output=True,
                           env=env, timeout=60)
    except (OSError, subprocess.TimeoutExpired) as e:
        raise RenderError(f"the guards' loader could not run: {type(e).__name__}")
    vals = r.stdout.decode("utf-8", "replace").split("\0")
    if r.returncode != 0 or len(vals) != 2 * len(ROOT_KEYS) + 1:
        raise RenderError(f"the guards' loader failed (exit {r.returncode})")
    for k, raw in zip(ROOT_KEYS, vals[0::2]):
        _refuse_unsafe(k, raw)
    return dict(zip(ROOT_KEYS, vals[1::2]))


def _refuse_unsafe(k: str, v: str) -> None:
    if "*" in v or "?" in v:
        raise RenderError(f"{k}={v!r} contains a wildcard character; a deny rule would match "
                          "more than that folder")
    if "\n" in v or "\r" in v:
        raise RenderError(f"{k} contains a line break")


def worktree(root: Path) -> str | None:
    """OpenCode's worktree: the git top level, or None (OpenCode then uses "/", READ project.ts)."""
    try:
        r = subprocess.run(["git", "-C", str(root), "rev-parse", "--show-toplevel"],
                           capture_output=True, timeout=30)
    except (OSError, subprocess.TimeoutExpired):
        return None
    out = r.stdout.decode("utf-8", "replace").strip()
    return oc_posix(out) if r.returncode == 0 and out else None


def _inside(p: str, w: str) -> str | None:
    """P relative to W ("." for W itself), or None when P is not inside W."""
    a, b = oc_posix(p), oc_posix(w)
    if sys.platform == "win32":
        a_cmp, b_cmp = a.lower(), b.lower()
    else:
        a_cmp, b_cmp = a, b
    if a_cmp == b_cmp:
        return "."
    if a_cmp.startswith(b_cmp.rstrip("/") + "/"):
        return a[len(b.rstrip("/")) + 1:]
    return None


def rules(roots: dict[str, str], wt: str | None) -> dict[str, dict[str, str]]:
    for k, v in roots.items():
        _refuse_unsafe(k, v)
    ref = roots.get("X4_REFERENCE") or ""
    if not ref.strip() or not oc_driveless(ref):
        raise RenderError("X4_REFERENCE is unresolved or the filesystem root")
    edit: dict[str, str] = {}

    def forms(p: str) -> list[str]:
        out = ["*" + oc_driveless(p)]
        rel = _inside(p, wt) if wt else None
        if rel is not None:
            out.append(rel)
        return out

    for f in forms(ref):
        edit[("*" if f == "." else f + "/*")] = "deny"
    for key in ARCHIVE_ROOTS:
        p = roots.get(key) or ""
        if not p.strip() or not oc_driveless(p):
            continue
        for f in forms(p):
            for ext in ARCHIVE_EXTS:
                edit[("*" if f == "." else f + "/*") + ext] = "deny"
    d = oc_driveless(ref)
    bash: dict[str, str] = {}
    for verb in DELETE_VERBS:
        for tail in (f"{d}/*", f"{d} *", f"{d}' *", f'{d}" *'):
            bash[f"{verb} *{tail}"] = "deny"
    return {"edit": edit, "bash": bash}


def render(root: Path) -> str:
    root_s = str(root)
    if "\n" in root_s or "\r" in root_s:
        raise RenderError("the install root contains a newline")
    perm = rules(resolve_roots(root), worktree(root))
    body = {"$schema": SCHEMA, "instructions": [ADDENDUM], "permission": perm}
    head = (f"{BANNER_PREFIX} for {root_s} -- per machine; never commit.\n"
            "// OpenCode support is best effort, from docs, not measured. Re-run "
            "`python .opencode/hooks/opencode_config.py write --root .` after moving reference/ or the game.\n")
    return head + json.dumps(body, indent=2, ensure_ascii=False) + "\n"


def _current(root: Path) -> str | None:
    p = root / CONFIG_REL
    if not p.is_file():
        return None
    try:
        return p.read_bytes().decode("utf-8").replace("\r\n", "\n")
    except UnicodeDecodeError:
        return ""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="opencode_config", description=__doc__.splitlines()[0])
    ap.add_argument("action", choices=("render", "write", "check"))
    ap.add_argument("--root", required=True, help="the toolkit install root")
    a = ap.parse_args(argv)
    root = Path(a.root).resolve()
    try:
        text = render(root)
    except RenderError as e:
        print(f"REFUSING: {e}. Nothing was written; the OpenCode deny rules are NOT in place.", file=sys.stderr)
        return 2
    if a.action == "render":
        sys.stdout.write(text)
        return 0
    cur = _current(root)
    if a.action == "check":
        if cur == text:
            print(f"{CONFIG_REL} is fresh")
            return 0
        print(f"{CONFIG_REL} is {'missing' if cur is None else 'stale'}: run "
              f"python .opencode/hooks/opencode_config.py write --root .", file=sys.stderr)
        return 1
    if cur is not None and not cur.startswith(BANNER_PREFIX):
        print(f"REFUSING: {root / CONFIG_REL} exists and is not ours (no banner); it is left as it is. "
              "Merge the rules from `render` into it by hand.", file=sys.stderr)
        return 3
    p = root / CONFIG_REL
    p.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode("utf-8")              # encode FIRST: a failed encode cannot truncate
    p.write_bytes(data)
    if p.read_bytes() != data:
        print(f"REFUSING: {p} did not read back as written", file=sys.stderr)
        return 2
    print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
